# -*- coding: utf-8 -*-
"""Dissertation NLP_Full_Pipeline .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13m1DwW-XDVWab82Mq2wPZGvdz59NLJsG

# Full NLP Pipeline — AI in Supply Chain Resilience within Industry 5.0

End-to-end: data collection -> keyword filtering -> preprocessing -> topic
modelling -> sentiment analysis -> co-occurrence analysis -> hypothesis
evidence summary -> visualisations -> final dataset export.

Follows the methodology chapter's "NLP Corpus Data Collection" and "NLP Data
Analysis" sections exactly: BeautifulSoup collection from six source
categories, keyword filtering (>=2 of 3 theme sets retained), spaCy
preprocessing, BERTopic topic modelling, RoBERTa sentiment analysis, and
co-occurrence analysis testing whether AI/resilience/Industry 5.0 terms
appear together more than chance.

**Sections:**
1. Install libraries
2. Setup & configuration
3. Define URL dataset (5 source categories + academic supplement)
4. Check & harvest URLs (parallel)
5. Scrape webpages (parallel)
6. Extract text (HTML + PDF)
7. Clean dataset
8. Build datapoints (sentence + paragraph level)
9. Keyword tagging & document-level filtering (>=2 of 3 themes retained)
10. Preprocessing (spaCy: lemmatisation, stopword removal)
11. Topic modelling (BERTopic)
12. Sentiment analysis (RoBERTa)
13. Co-occurrence analysis (4 levels)
14. Hypothesis evidence summary (H1, H2, H3)
15. Visualisations & descriptive statistics
16. Save final dataset

## 1. Install libraries
"""

!pip install -q requests beautifulsoup4 lxml pandas numpy pymupdf scipy matplotlib seaborn
!pip install -q spacy scikit-learn openpyxl
!pip install -q bertopic sentence-transformers
!pip install -q transformers torch --index-url https://download.pytorch.org/whl/cpu
!python -m spacy download en_core_web_sm -q
print("Libraries installed.")

"""## 2. Setup & configuration"""

import os
import re
import time
import random
import hashlib
import collections
from urllib.parse import urljoin, urlparse
from concurrent.futures import ThreadPoolExecutor, as_completed

import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from bs4 import BeautifulSoup
import fitz  # PyMuPDF

os.makedirs("corpus", exist_ok=True)
os.makedirs("outputs", exist_ok=True)
os.makedirs("outputs/charts", exist_ok=True)

print("Setup complete.")

DOCUMENT_REFERENCE_POINT = 100     # Used for informational purposes for the scraping size, not a hard minimum.
DATAPOINT_REFERENCE_POINT = 2000   # Used for informational purposes for the scraping size, not a hard minimum.

REQUEST_TIMEOUT = 20
MAX_CHECK_WORKERS = 15   # concurrent URL-reachability checks
MAX_SCRAPE_WORKERS = 15  # concurrent page fetches

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (compatible; AcademicResearchBot/1.0; "
        "+mailto:REPLACE_WITH_YOUR_UNIVERSITY_EMAIL) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
    "Connection": "keep-alive",
}

# ============================================================
# ETHICAL SCRAPING POLICY (state this in your methodology /
# ethics chapter - matches "publicly accessible... no personal
# data on identifiable individuals" claim in the methodology PDF)
# 1. robots.txt is checked before every page request; a
#    disallowed URL is skipped, never overridden.
# 2. No personal data is collected: author bio pages, staff
#    directories, comment sections, forum/user-profile URLs,
#    and social-media pages are excluded by URL pattern.
# 3. Requests identify as an academic research crawler (see
#    User-Agent above) rather than impersonating a browser.
# ============================================================
import threading
from urllib.robotparser import RobotFileParser

PERSONAL_DATA_URL_PATTERNS = [
    "/author/", "/profile/", "/user/", "/member/", "/comments/",
    "/forum/", "/community/", "linkedin.com/in/", "facebook.com/",
    "twitter.com/", "x.com/", "instagram.com/",
]

_robots_cache = {}
_robots_lock = threading.Lock()


def is_scraping_allowed(url):
    """
    Checks robots.txt (cached per domain, thread-safe) and
    filters out personal-data-looking URLs. Fetches robots.txt
    with a short explicit timeout rather than RobotFileParser's
    own .read() (which has no timeout and can hang on a slow site).
    """
    lowered = url.lower()
    if any(p in lowered for p in PERSONAL_DATA_URL_PATTERNS):
        return False
    try:
        parsed = urlparse(url)
        base = f"{parsed.scheme}://{parsed.netloc}"
        with _robots_lock:
            cached = _robots_cache.get(base, "MISS")
        if cached == "MISS":
            rp = RobotFileParser()
            try:
                resp = requests.get(f"{base}/robots.txt", headers=HEADERS, timeout=5)
                rp.parse(resp.text.splitlines())
            except Exception:
                rp = None
            with _robots_lock:
                _robots_cache[base] = rp
            cached = rp
        return True if cached is None else cached.can_fetch(HEADERS["User-Agent"], url)
    except Exception:
        return False


print(f"Reference points: >= {DOCUMENT_REFERENCE_POINT} documents, >= {DATAPOINT_REFERENCE_POINT} datapoints (no ceiling)")
print("Ethical scraping controls active: robots.txt compliance + personal-data URL filtering")

"""## 3. Define URL dataset

Organised into the Six source categories
"""

INCLUDE_SUPPLEMENTARY_ACADEMIC = True

CAT1_EC_GOVERNMENT = [
    ("https://research-and-innovation.ec.europa.eu/research-area/industrial-research-and-innovation/industry-50_en", "European Commission", "html", "H2"),
    ("https://single-market-economy.ec.europa.eu/industry/strategy/advanced-technologies/industrial-applications-artificial-intelligence-and-big-data_en", "European Commission", "html", "H2"),
    ("https://single-market-economy.ec.europa.eu/industry/strategy/digital-transformation_en", "European Commission", "html", "H1"),
    ("https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A52020DC0474", "European Commission (EUR-Lex)", "html", "H1"),
    ("https://cordis.europa.eu/project/id/101112089", "European Commission (CORDIS - AIMS5.0 project)", "html", "H3"),
    ("https://digital-strategy.ec.europa.eu/en/policies/apply-ai", "European Commission", "html", "H1"),
    ("https://digital-strategy.ec.europa.eu/en/policies/artificial-intelligence", "European Commission", "html", "H1"),
    ("https://digital-strategy.ec.europa.eu/en/policies/european-approach-artificial-intelligence", "European Commission", "html", "H1"),
]

CAT2_INTERNATIONAL_ORGS = [
    ("https://www.weforum.org/agenda/2023/01/supply-chain-resilience-artificial-intelligence/", "World Economic Forum", "html", "H2"),
    ("https://www.weforum.org/agenda/2022/05/how-to-build-resilient-supply-chains/", "World Economic Forum", "html", "H2"),
    ("https://www.weforum.org/stories/2025/01/ai-supply-chains/", "World Economic Forum", "html", "H2"),
    ("https://www.weforum.org/publications/artificial-intelligence-for-efficiency-sustainability-and-inclusivity-in-tradetech/", "World Economic Forum", "html", "H2"),
    ("https://www.oecd.org/en/publications/strengthening-supply-chains-through-efficiency-resilience-ai-and-environmental-performance_2a495d96-en/full-report.html", "OECD", "html", "H1"),
    ("https://www.oecd.org/en/publications/strengthening-supply-chains-through-efficiency-resilience-ai-and-environmental-performance_2a495d96-en.html", "OECD", "html", "H1"),
    ("https://www.oecd.org/en/publications/strengthening-supply-chains-through-efficiency-resilience-ai-and-environmental-performance_2a495d96-en/full-report/component-6.html", "OECD", "html", "H1"),
    ("https://www.oecd.org/en/publications/strengthening-supply-chains-through-efficiency-resilience-ai-and-environmental-performance_2a495d96-en/full-report/component-7.html", "OECD", "html", "H1"),
    ("https://www.oecd.org/en/publications/2025/06/oecd-supply-chain-resilience-review_9930d256.html", "OECD", "html", "H1"),
    ("https://www.oecd.org/en/about/news/speech-statements/2025/06/2025-oecd-supply-chain-resilience-review-launch.html", "OECD", "html", "H1"),
    ("https://www.oecd.org/content/dam/oecd/en/publications/reports/2025/06/oecd-supply-chain-resilience-review_9930d256/94e3a8ea-en.pdf", "OECD", "pdf", "H1"),
    ("https://www.ilo.org/resource/statement/ilc/ilc114/opening-address-ilo-director-general-international-labour-conference", "ILO", "html", "H2"),
    ("https://www.ilo.org/resource/conference-paper/ilc/ilc114/moment-choice-harnessing-artificial-intelligence-decent-work-report", "ILO", "html", "H2"),
    ("https://www.ilo.org/artificial-intelligence-and-work-digital-economy", "ILO", "html", "H2"),
    ("https://www.just-style.com/news/ilo-ai-knowledge-hub-labour/", "ILO (via Just Style)", "html", "H1"),
    ("https://www.weforum.org/press/2026/01/global-supply-chains-enter-era-of-structural-volatility-world-economic-forum-report-finds/", "World Economic Forum", "html", "H1"),
    ("https://reports.weforum.org/docs/WEF_Global_Value_Chains_Outlook_2026.pdf", "World Economic Forum", "pdf", "H1"),
    ("https://www.oecd.org/content/dam/oecd/en/publications/reports/2026/06/strengthening-supply-chains-through-efficiency-resilience-ai-and-environmental-performance_c776c9ff/2a495d96-en.pdf", "OECD", "pdf", "H1"),
]

CAT3_CONSULTING = [
    ("https://www.mckinsey.com/capabilities/operations/our-insights/supply-chain-resilience-getting-ahead-of-the-next-disruption", "McKinsey", "html", "H1"),
    ("https://www.mckinsey.com/capabilities/operations/our-insights/how-covid-19-is-reshaping-supply-chains", "McKinsey", "html", "H1"),
    ("https://www.mckinsey.com/capabilities/operations/our-insights/supply-chain-risk-survey-2024", "McKinsey", "html", "H1"),
    ("https://www.mckinsey.com/industries/industrials/our-insights/distribution-blog/harnessing-the-power-of-ai-in-distribution-operations", "McKinsey", "html", "H1"),
    ("https://www.mckinsey.com/industries/metals-and-mining/our-insights/succeeding-in-the-ai-supply-chain-revolution", "McKinsey", "html", "H1"),
    ("https://www.mckinsey.com/capabilities/operations/our-insights/beyond-automation-how-gen-ai-is-reshaping-supply-chains", "McKinsey", "html", "H1"),
    ("https://www.mckinsey.com/capabilities/operations/our-insights/tech-enabled-transformations-three-supply-chain-success-stories", "McKinsey", "html", "H1"),
    ("https://www.mckinsey.com/capabilities/operations/our-insights/future-proofing-the-supply-chain", "McKinsey", "html", "H1"),
    ("https://www.mckinsey.com/featured-insights/mckinsey-explainers/what-is-supply-chain", "McKinsey", "html", "H1"),
    ("https://www.mckinsey.com/capabilities/operations/our-insights/operations-blog/building-the-supply-chain-of-tomorrow-an-integrated-approach", "McKinsey", "html", "H1"),
    ("https://www.mckinsey.com/capabilities/operations/our-insights/decoding-disruption-to-reshape-manufacturing-footprints", "McKinsey", "html", "H1"),
    ("https://www2.deloitte.com/us/en/insights/focus/supply-chain-management/building-supply-chain-resilience.html", "Deloitte", "html", "H1"),
    ("https://www.deloitte.com/us/en/insights/industry/manufacturing-industrial-products/agentic-supply-chain-artificial-intelligence-manufacturing.html", "Deloitte", "html", "H3"),
    ("https://www.deloitte.com/us/en/services/consulting/articles/ai-in-supply-chain.html", "Deloitte", "html", "H1"),
    ("https://www.deloitte.com/dk/en/services/consulting/research/supply-chain-resilience-report-2022.html", "Deloitte", "html", "H1"),
    ("https://www.deloitte.com/us/en/insights/industry/retail-distribution/retail-distribution-industry-outlook.html", "Deloitte", "html", "H1"),
    ("https://www.bcg.com/publications/2024/emerging-resilience-in-semiconductor-supply-chain", "BCG", "html", "H1"),
    ("https://www.bcg.com/publications/2024/genai-reimagines-supply-chain", "BCG", "html", "H1"),
    ("https://www.bcg.com/publications/2025/cost-resilience-new-supply-chain-challenge", "BCG", "html", "H1"),
    ("https://www.bcg.com/publications/2026/supply-chain-planning-why-ai-alone-isnt-enough", "BCG", "html", "H3"),
    ("https://www.bcg.com/publications/2021/building-resilience-strategies-to-improve-supply-chain-resilience", "BCG", "html", "H1"),
    ("https://www.bcg.com/news/13june2025-build-resilient-supply-chain", "BCG", "html", "H1"),
    ("https://www.bcg.com/x/product-library/supply-chain-ai", "BCG", "html", "H1"),
    ("https://www.bcg.com/publications/2022/benefits-of-ai-driven-supply-chain", "BCG", "html", "H1"),
    ("https://www.bcg.com/publications/2026/ai-is-already-moving-the-logistics-industry-forward", "BCG", "html", "H1"),
    ("https://www.pwc.com/gx/en/issues/transformation/smart-moves-your-supply-chains-needs.html", "PwC", "html", "H1"),
    ("https://www.pwc.com/gx/en/industries/industrial-manufacturing/digital-supply-chain.html", "PwC", "html", "H1"),
    ("https://www.ey.com/en_us/simply-explained/ai-powered-supply-chains", "EY", "html", "H1"),
    ("https://www.ey.com/en_us/insights/coo/autonomous-supply-chain-planning-with-ai", "EY", "html", "H1"),
    ("https://www.ey.com/en_be/insights/supply-chain/transforming-supply-chains-with-ai-achieving-agility-and-efficiency", "EY", "html", "H1"),
    ("https://www.ey.com/en_us/insights/coo/resilient-supply-chains-need-more-risk-awareness-and-ai", "EY", "html", "H1"),
    # Accenture
    ("https://www.accenture.com/us-en/blogs/supply-chain/autonomous-supply-chain-cyber-resilience", "Accenture", "html", "H1"),
    ("https://www.accenture.com/us-en/insights/supply-chain/making-autonomous-supply-chains-real", "Accenture", "html", "H1"),
    ("https://www.accenture.com/us-en/services/supply-chain/autonomous-supply-chain", "Accenture", "html", "H1"),
    ("https://www.accenture.com/us-en/services/supply-chain/supply-chain-strategy", "Accenture", "html", "H1"),
    ("https://www.accenture.com/us-en/blogs/supply-chain/maximize-value-ai-planning", "Accenture", "html", "H1"),
    ("https://www.accenture.com/us-en/insights/supply-chain/making-self-funding-supply-chains-real", "Accenture", "html", "H1"),
]

CAT4_CORPORATE_REPORTS = [
    ("https://www.maersk.com/~/media_sc9/maersk/corporate/sustainability/files/resources/2024/maersk-annual-report-2024.pdf", "Maersk", "pdf", "H1"),
    ("https://www.maersk.com/insights/logistics-trend-map/artificial-intelligence-in-logistics", "Maersk", "html", "H1"),
    ("https://www.maersk.com/insights/digitalisation/2024/12/18/what-to-expect-in-2025-supply-chain-tech-trends", "Maersk", "html", "H1"),
    ("https://www.maersk.com/insights/digitalisation/2025/05/06/transforming-supply-chains-with-hyperconnectivity", "Maersk", "html", "H1"),
    ("https://www.maersk.com/insights/resilience/2025/06/05/course-for-change-resilience-report", "Maersk", "html", "H1"),
    ("https://www.ibm.com/case-studies/ibm-supply-chain", "IBM", "html", "H1"),
    ("https://www.ibm.com/think/topics/supply-chain-resiliency", "IBM", "html", "H1"),
    ("https://www.ibm.com/resources/business-operations/supply-chain-sustainability", "IBM", "html", "H1"),
    ("https://newsroom.ibm.com/2022-09-20-IBM-Study-Supply-Chain-Leaders-Are-Investing-in-AI-and-Automation-to-Navigate-Supply-Chain-Uncertainties-and-Improve-Sustainability", "IBM", "html", "H1"),
    ("https://www.ibm.com/think/topics/supply-chain-resiliency-for-industrial", "IBM", "html", "H1"),
    ("https://www.ibm.com/thought-leadership/institute-business-value/en-us/report/supply-chain-ai-automation-oracle", "IBM", "html", "H1"),
    ("https://www.ibm.com/think/insights/agentic-ai-helps-coo-csco-lead-resilient-supply-chains", "IBM", "html", "H1"),
    ("https://www.ibm.com/think/insights/ai-driven-integration-reduces-supply-chain-exceptions-accelerates-decision-making", "IBM", "html", "H1"),
    ("https://blogs.sap.com/2023/07/05/resiliency-with-ai-in-supply-chain", "SAP", "html", "H1"),
    ("https://news.sap.com/2026/02/blueprint-for-supply-chain-resilience-in-2026/", "SAP", "html", "H1"),
    ("https://www.siemens.com/en-us/company/sustainability/infrastructure-transition-monitor-report/industry/", "Siemens", "html", "H1"),
]

CAT5_TRADE_PRESS = [
    ("https://supplychaindigital.com/supply-chain-risk-management/ai-in-supply-chain-management", "Supply Chain Digital", "html", "H1"),
    ("https://supplychaindigital.com/technology/industry-5-0-what-does-it-mean-for-supply-chain", "Supply Chain Digital", "html", "H2"),
    ("https://supplychaindigital.com/news/role-of-ai-supply-chain-efficiency", "Supply Chain Digital", "html", "H1"),
    ("https://supplychaindigital.com/technology/bcg-future-factories-ai", "Supply Chain Digital", "html", "H1"),
    ("https://supplychaindigital.com/news/global-manufacturers-look-to-ai-in-supply-chain", "Supply Chain Digital", "html", "H1"),
    ("https://www.supplychainbrain.com/articles/38742-how-ai-is-transforming-supply-chain-resilience", "Supply Chain Brain", "html", "H1"),
    ("https://www.manufacturingdive.com/news/agentic-ai-potential-rattle-manufacturing-status-quo-deloitte/816325/", "Manufacturing Dive", "html", "H3"),
    ("https://aimagazine.com/news/ai-to-redefine-manufacturing-competitiveness-in-2026", "AI Magazine", "html", "H1"),
    ("https://openskygroup.com/supply-chain-ai-statistics/", "Open Sky Group", "html", "H1"),
    ("https://resiliencefirst.org/news/artificial-intelligence-for-supply-chain-resilience-a-qa-with-deloitte-insights/", "Resilience First", "html", "H3"),
    ("https://www.intelycx.com/resources/industry-5-0/", "Intelycx", "html", "H2"),
    ("https://www.dcvelocity.com/articles/59073-risk-and-resilience-are-the-top-topics-in-mckinsey-supply-chain-survey", "DC Velocity", "html", "H1"),
    ("https://procurementmag.com/news/ai-alone-failing-fix-supply-chain", "Procurement Magazine", "html", "H1"),
    ("https://procurementmag.com/news/procurement-leaders-deploying-ai-manufacturing", "Procurement Magazine", "html", "H1"),
    ("https://cxtms.com/blog/ai-implementation-gap-supply-chain-planning-bcg-report-2026", "CXTMS", "html", "H1"),
    ("https://sapinsider.org/sap-pushes-agentic-ai-to-center-of-supply-chain-resilience-strategy/", "SAP Insider", "html", "H1"),
    ("https://www.forbes.com/sites/sap/2025/09/17/the-roi-of-resilience-supply-chains-finance-and-ai/", "Forbes (SAP BrandVoice)", "html", "H1"),
    ("https://www.pymnts.com/artificial-intelligence-2/2025/from-just-in-time-to-just-in-case-inside-schneider-electrics-ai-powered-supply-chain", "PYMNTS", "html", "H1"),
    ("https://manufacturingdigital.com/news/how-global-manufacturers-are-using-ai-in-supply-chains", "Manufacturing Digital", "html", "H1"),
    ("https://www.gartner.com/en/newsroom/press-releases/2026-06-17-gartner-announces-2026-rankings-of-the-global-supply-chain-top-25", "Gartner", "html", "H1"),
    ("https://supplychaindigital.com/news/accenture-on-autonomous-supply-chains", "Supply Chain Digital", "html", "H1"),
    ("https://procurementmag.com/news/accenture-how-ai-drives-higher-supply-chain-margins", "Procurement Magazine", "html", "H1"),
    ("https://aimagazine.com/ai-strategy/accenture-ai-rewiring-supply-chains", "AI Magazine", "html", "H1"),
    ("https://global.fujitsu/en-global/insight/tl-scm-digital-rehearsal-202600302", "Fujitsu Global", "html", "H1"),
    ("https://www.portcast.io/blog/building-ai-enabled-supply-chain-resilience-the-portcast-and-siemens-collaboration", "Portcast", "html", "H1"),
    ("https://supplychaindigital.com/news/the-ai-innovations-driving-supply-chain-resilience", "Supply Chain Digital", "html", "H1"),
    ("https://www.scmr.com/article/how-ai-and-digital-twins-are-rewriting-the-rules-of-supply-chain-recovery", "Supply Chain Management Review", "html", "H1"),
    ("https://www.supplychainreview.org/en/articles/gartner-2026-supply-chain-top-25-ai-ecosystem", "Supply Chain Review", "html", "H1"),
]

SUPPLEMENTARY_ACADEMIC_SOURCES = [
    ("https://link.springer.com/article/10.1007/s13132-024-01999-6", "Journal of the Knowledge Economy", "html", "H3"),
    ("https://www.frontiersin.org/journals/sustainability/articles/10.3389/frsus.2025.1584580/full", "Frontiers in Sustainability", "html", "H3"),
    ("https://pmc.ncbi.nlm.nih.gov/articles/PMC9886400/", "PMC (NIH)", "html", "H3"),
    ("https://www.mdpi.com/2078-2489/16/1/26", "MDPI Information", "html", "H1"),
    ("https://pubmed.ncbi.nlm.nih.gov/36741206/", "PubMed", "html", "H3"),
    ("https://pmc.ncbi.nlm.nih.gov/articles/PMC12298069/", "PMC (NIH)", "html", "H2"),
    ("https://www.mdpi.com/1999-5903/17/9/430", "MDPI Future Internet", "html", "H2"),
    ("https://www.mdpi.com/2673-4591/97/1/25", "MDPI Engineering Proceedings", "html", "H3"),
    ("https://www.mdpi.com/2071-1050/16/16/7110", "MDPI Sustainability", "html", "H2"),
    ("https://www.mdpi.com/2076-3417/16/5/2617", "MDPI Applied Sciences", "html", "H2"),
    ("https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11788849/", "PMC (NIH)", "html", "H1"),
    ("https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10966127/", "PMC (NIH) - ILO co-authored", "html", "H2"),
]

VERIFIED_SOURCES = (
    [(u, o, d, h, "European Commission and Government Publications") for u, o, d, h in CAT1_EC_GOVERNMENT] +
    [(u, o, d, h, "International Organisation Reports and Whitepapers") for u, o, d, h in CAT2_INTERNATIONAL_ORGS] +
    [(u, o, d, h, "Management Consulting Industry Reports") for u, o, d, h in CAT3_CONSULTING] +
    [(u, o, d, h, "Corporate Annual Reports and Sustainability Reports") for u, o, d, h in CAT4_CORPORATE_REPORTS] +
    [(u, o, d, h, "Industry and Trade Publications") for u, o, d, h in CAT5_TRADE_PRESS]
)
if INCLUDE_SUPPLEMENTARY_ACADEMIC:
    VERIFIED_SOURCES += [(u, o, d, h, "Supplementary Academic (outside 5-category methodology)")
                          for u, o, d, h in SUPPLEMENTARY_ACADEMIC_SOURCES]

print("Verified sources by category:")
for cat, n in collections.Counter(cat for *_, cat in VERIFIED_SOURCES).items():
    print(f"  {cat:<55} {n}")
print(f"\nTotal verified sources: {len(VERIFIED_SOURCES)}")

LISTING_PAGES = [
    ("https://www.oecd.org/en/topics/trade-facilitation.html", "OECD", "html"),
    ("https://www.weforum.org/topics/supply-chains/", "World Economic Forum", "html"),
    ("https://www.ilo.org/artificial-intelligence-and-work-digital-economy", "ILO", "html"),
    ("https://www.mckinsey.com/capabilities/operations/our-insights", "McKinsey", "html"),
    ("https://www.bcg.com/capabilities/operations/insights", "BCG", "html"),
    ("https://www.pwc.com/gx/en/industries/industrial-manufacturing/digital-supply-chain.html", "PwC", "html"),
    ("https://www.accenture.com/us-en/insights/supply-chain-operations", "Accenture", "html"),
    ("https://www.ibm.com/think/topics/supply-chain-management", "IBM", "html"),
    ("https://blogs.sap.com/tag/supply-chain-management/", "SAP", "html"),
    ("https://www.maersk.com/insights/resilience", "Maersk", "html"),
    ("https://supplychaindigital.com/technology", "Supply Chain Digital", "html"),
    ("https://www.supplychainbrain.com/topics/24-technology", "Supply Chain Brain", "html"),
    ("https://supplychaindigital.com/technology/ai-in-supply-chain-management", "Supply Chain Digital", "html"),
    ("https://www.mdpi.com/search?q=%22industry%205.0%22%20%22supply%20chain%22", "MDPI (Open Access)", "html"),
    ("https://www.frontiersin.org/search?query=AI%20supply%20chain%20resilience", "Frontiers (Open Access)", "html"),
    ("https://pmc.ncbi.nlm.nih.gov/?term=industry+5.0+supply+chain+artificial+intelligence", "PMC (NIH)", "html"),
]

RELEVANCE_TERMS = [
    "supply-chain", "supply chain", "resilien", "artificial-intelligence",
    "artificial intelligence", " ai-", "-ai-", "ai in", "industry-5", "industry 5",
    "generative-ai", "genai", "logistics", "procurement", "digital-supply",
    "automation", "machine-learning", "predictive", "human-centric", "sustainab"
]

CATEGORY_LOOKUP = {
    "oecd.org": "International Organisation Reports and Whitepapers",
    "weforum.org": "International Organisation Reports and Whitepapers",
    "ilo.org": "International Organisation Reports and Whitepapers",
    "mckinsey.com": "Management Consulting Industry Reports",
    "bcg.com": "Management Consulting Industry Reports",
    "pwc.com": "Management Consulting Industry Reports",
    "accenture.com": "Management Consulting Industry Reports",
    "ibm.com": "Corporate Annual Reports and Sustainability Reports",
    "sap.com": "Corporate Annual Reports and Sustainability Reports",
    "maersk.com": "Corporate Annual Reports and Sustainability Reports",
    "supplychaindigital.com": "Industry and Trade Publications",
    "supplychainbrain.com": "Industry and Trade Publications",
    "mdpi.com": "Supplementary Academic (outside 5-category methodology)",
    "frontiersin.org": "Supplementary Academic (outside 5-category methodology)",
    "ncbi.nlm.nih.gov": "Supplementary Academic (outside 5-category methodology)",
}

def category_for_url(url, fallback="Industry and Trade Publications"):
    for domain_part, cat_name in CATEGORY_LOOKUP.items():
        if domain_part in url:
            return cat_name
    return fallback

print(f"Listing pages: {len(LISTING_PAGES)} | Relevance terms: {len(RELEVANCE_TERMS)}")

"""## 4. Check & harvest URLs (parallel)

Harvests on-topic links from listing pages, merges with verified sources, checks reachability - all concurrently. robots.txt and personal-data URLs are excluded at every step (see Section 2).
"""

def harvest_links_from_listing_page(url, org_name, doc_type):
    if not is_scraping_allowed(url):
        return (org_name, url, [], "robots.txt disallowed / personal-data URL")
    try:
        response = requests.get(url, headers=HEADERS, timeout=REQUEST_TIMEOUT)
        response.raise_for_status()
    except Exception as e:
        return (org_name, url, [], str(e)[:60])

    soup = BeautifulSoup(response.text, "html.parser")
    domain = urlparse(url).netloc
    found = []
    for a in soup.find_all("a", href=True):
        href = urljoin(url, a["href"])
        link_text = a.get_text(" ", strip=True).lower()
        if urlparse(href).netloc != domain:
            continue
        if any(p in href.lower() for p in PERSONAL_DATA_URL_PATTERNS):
            continue
        haystack = (href + " " + link_text).lower()
        if any(term in haystack for term in RELEVANCE_TERMS):
            found.append(href)
    return (org_name, url, list(dict.fromkeys(found)), None)


print(f"Harvesting from {len(LISTING_PAGES)} listing pages (parallel)...")
print("-" * 65)

harvested = []
with ThreadPoolExecutor(max_workers=MAX_CHECK_WORKERS) as executor:
    futures = [executor.submit(harvest_links_from_listing_page, url, org, dtype)
               for url, org, dtype in LISTING_PAGES]
    for future in as_completed(futures):
        org_name, url, links, err = future.result()
        if err:
            print(f"  {org_name:<24} FAILED: {err}")
        else:
            print(f"  {org_name:<24} -> {len(links)} on-topic links")
            category = category_for_url(url)
            for link in links:
                harvested.append((link, org_name, "html", "harvested", category))

print("-" * 65)
print(f"Total harvested candidates: {len(harvested)}")

seen = set()
all_candidates = []
for url, org, doc_type, tag, category in VERIFIED_SOURCES:
    if url not in seen:
        seen.add(url)
        all_candidates.append((url, org, doc_type, tag, category))
for url, org, doc_type, tag, category in harvested:
    if url not in seen:
        seen.add(url)
        all_candidates.append((url, org, doc_type, tag, category))

print(f"Combined candidate pool: {len(all_candidates)} URLs "
      f"({len(VERIFIED_SOURCES)} verified + {len(harvested)} harvested, deduplicated)")

check_failures = []

def check_url(entry):
    url, org, declared_type, tag, category = entry
    if not is_scraping_allowed(url):
        return None, (url, org, "robots.txt disallowed / personal-data URL")
    try:
        r = requests.get(url, headers=HEADERS, timeout=REQUEST_TIMEOUT, stream=True, allow_redirects=True)
        if r.status_code >= 400:
            return None, (url, org, f"HTTP {r.status_code}")
        content_type = r.headers.get("Content-Type", "").lower()
        actual_type = "pdf" if ("pdf" in content_type or url.lower().endswith(".pdf")) else "html"
        return (url, org, actual_type, tag, category), None
    except requests.exceptions.Timeout:
        return None, (url, org, "timeout")
    except requests.exceptions.SSLError:
        return None, (url, org, "SSL error")
    except requests.exceptions.ConnectionError as e:
        return None, (url, org, f"connection error: {str(e)[:40]}")
    except Exception as e:
        return None, (url, org, f"error: {str(e)[:40]}")


print(f"Checking {len(all_candidates)} candidate URLs (parallel, {MAX_CHECK_WORKERS} workers)...")
print("-" * 65)

checked_candidates = []
with ThreadPoolExecutor(max_workers=MAX_CHECK_WORKERS) as executor:
    futures = [executor.submit(check_url, entry) for entry in all_candidates]
    completed = 0
    for future in as_completed(futures):
        result, failure = future.result()
        completed += 1
        if result:
            checked_candidates.append(result)
        else:
            check_failures.append(failure)
        if completed % 25 == 0 or completed == len(futures):
            print(f"  Checked {completed}/{len(futures)} - {len(checked_candidates)} reachable so far")

print("-" * 65)
print(f"Reachable URLs: {len(checked_candidates)} / {len(all_candidates)}")
print("By type:", pd.Series([t for _, _, t, _, _ in checked_candidates]).value_counts().to_dict())
print("By category:")
print(pd.Series([c for *_, c in checked_candidates]).value_counts())

if check_failures:
    fail_df = pd.DataFrame(check_failures, columns=["url", "org_name", "reason"])
    fail_df.to_csv("outputs/check_url_failures.csv", index=False)
    print(f"\n{len(check_failures)} failed - reasons saved to outputs/check_url_failures.csv")

pd.DataFrame(checked_candidates, columns=["url", "org_name", "doc_type", "hypothesis_tag", "source_category"]) \
    .to_csv("outputs/url_dataset.csv", index=False)
print("Saved outputs/url_dataset.csv")

"""## 5. Scrape webpages (parallel)"""

def fetch_content(entry):
    url, org, doc_type, tag, category = entry
    if not is_scraping_allowed(url):
        return (url, org, doc_type, tag, category, None, "skipped: robots.txt / personal-data URL")
    try:
        r = requests.get(url, headers=HEADERS, timeout=REQUEST_TIMEOUT)
        r.raise_for_status()
        if doc_type == "pdf":
            return (url, org, doc_type, tag, category, r.content.hex(), "ok")
        return (url, org, doc_type, tag, category, r.text, "ok")
    except Exception as e:
        return (url, org, doc_type, tag, category, None, f"failed: {str(e)[:60]}")


url_df = pd.read_csv("outputs/url_dataset.csv")
entries = list(url_df.itertuples(index=False, name=None))

print(f"Scraping {len(entries)} URLs (parallel, {MAX_SCRAPE_WORKERS} workers)...")
print("-" * 65)

scrape_results = []
with ThreadPoolExecutor(max_workers=MAX_SCRAPE_WORKERS) as executor:
    futures = [executor.submit(fetch_content, entry) for entry in entries]
    completed = 0
    for future in as_completed(futures):
        result = future.result()
        scrape_results.append(result)
        completed += 1
        if completed % 25 == 0 or completed == len(futures):
            ok_so_far = sum(1 for r in scrape_results if r[-1] == "ok")
            print(f"  Progress: {completed}/{len(futures)} attempted, {ok_so_far} succeeded")

scrape_df = pd.DataFrame(scrape_results, columns=[
    "url", "org_name", "doc_type", "hypothesis_tag", "source_category", "raw_content", "status"
])
scrape_df.to_csv("outputs/scrape_progress.csv", index=False)

print("-" * 65)
print(f"Scraping complete: {(scrape_df['status'] == 'ok').sum()} / {len(scrape_df)} succeeded")

"""## 6. Extract text (HTML + PDF)"""

def extract_html_text(html):
    soup = BeautifulSoup(html, "html.parser")
    for tag in soup(["nav", "header", "footer", "aside", "script",
                      "style", "form", "iframe", "button", "noscript"]):
        tag.decompose()
    main_content = (
        soup.find("main") or soup.find("article") or soup.find(id="content") or
        soup.find(class_="content") or soup.find(class_="article-body") or
        soup.find(class_="post-content") or soup.body
    )
    if main_content:
        paragraphs = main_content.find_all("p")
        # Join WITHIN each paragraph with a space, but keep paragraph breaks as \n\n
        # so downstream code can recover paragraph-level units (not just sentence-level)
        para_texts = [re.sub(r"\s+", " ", p.get_text(strip=True)) for p in paragraphs]
        para_texts = [p for p in para_texts if len(p) > 20]
        text = "\n\n".join(para_texts)
    else:
        text = re.sub(r"\s+", " ", soup.get_text(separator=" ", strip=True))
    return text.strip()


def extract_pdf_text(pdf_bytes):
    try:
        doc = fitz.open(stream=pdf_bytes, filetype="pdf")
        # Join pages with a paragraph break; PyMuPDF preserves some line structure per page
        page_texts = [re.sub(r"\s+", " ", page.get_text()).strip() for page in doc]
        doc.close()
        page_texts = [p for p in page_texts if len(p) > 20]
        return "\n\n".join(page_texts)
    except Exception:
        return ""

scrape_df = pd.read_csv("outputs/scrape_progress.csv")
ok_rows = scrape_df[scrape_df["status"] == "ok"].copy()

print(f"Extracting text from {len(ok_rows)} successfully scraped documents...")
print("-" * 65)

documents = []
for _, row in ok_rows.iterrows():
    if row["doc_type"] == "pdf":
        try:
            pdf_bytes = bytes.fromhex(row["raw_content"])
            text = extract_pdf_text(pdf_bytes)
        except Exception:
            text = ""
    else:
        text = extract_html_text(row["raw_content"]) if isinstance(row["raw_content"], str) else ""

    if len(text) > 300:
        documents.append({
            "url": row["url"], "org_name": row["org_name"], "doc_type": row["doc_type"],
            "hypothesis_tag": row["hypothesis_tag"], "source_category": row["source_category"],
            "text": text
        })

print(f"Documents with usable text (>300 chars): {len(documents)}")

"""## 7. Clean dataset

Produces `clean_text`: lowercased, punctuation/boilerplate-stripped, whitespace-normalised, with paragraph breaks preserved.
"""

def clean_text_for_analysis(text):
    # Clean each paragraph separately so paragraph breaks (\n\n) survive cleaning -
    # needed for the paragraph-level co-occurrence analysis in Section 10.
    paragraphs = text.split("\n\n")
    cleaned_paragraphs = []
    for para in paragraphs:
        para = para.lower()
        para = re.sub(r"http\S+|www\.\S+", " ", para)          # remove URLs
        para = re.sub(r"\S+@\S+", " ", para)                    # remove emails
        para = re.sub(r"[^a-z0-9.,!?;:'\-\s]", " ", para)       # strip odd symbols
        para = re.sub(r"\s+", " ", para).strip()
        if para:
            cleaned_paragraphs.append(para)
    return "\n\n".join(cleaned_paragraphs)

# Dedup (by URL and by content hash), then apply cleaning to build
# `cleaned_documents` - the input every later section depends on.
seen_urls_final = set()
seen_hashes = set()
cleaned_documents = []

for doc in documents:
    text_hash = hashlib.md5(doc["text"].encode("utf-8")).hexdigest()
    if doc["url"] in seen_urls_final or text_hash in seen_hashes:
        continue
    seen_urls_final.add(doc["url"])
    seen_hashes.add(text_hash)

    doc = dict(doc)
    doc["clean_text"] = clean_text_for_analysis(doc["text"])
    cleaned_documents.append(doc)

print(f"Documents before dedup: {len(documents)}")
print(f"Documents after dedup:  {len(cleaned_documents)}  (this is the corpus used from here on)")

"""## 8. Build datapoints (sentence + paragraph level)"""

def split_into_paragraphs(text):
    paras = text.split("\n\n")
    return [p.strip() for p in paras if len(p.strip()) > 40]


def split_into_sentences(text):
    # Operates within a single paragraph (no \n\n inside), so sentence boundaries
    # never accidentally straddle a paragraph break.
    raw_sentences = re.split(r"(?<=[.!?])\s+", text)
    return [s.strip() for s in raw_sentences if len(s.strip()) > 15]


datapoint_rows = []
paragraph_rows = []

for doc_id, doc in enumerate(cleaned_documents):
    paragraphs = split_into_paragraphs(doc["clean_text"])
    doc["paragraph_count"] = len(paragraphs)

    sent_id_counter = 0
    for para_id, paragraph in enumerate(paragraphs):
        paragraph_rows.append({
            "doc_id": doc_id, "paragraph_id": para_id, "url": doc["url"],
            "org_name": doc["org_name"], "source_category": doc["source_category"],
            "hypothesis_tag": doc["hypothesis_tag"], "paragraph": paragraph
        })
        for sentence in split_into_sentences(paragraph):
            datapoint_rows.append({
                "doc_id": doc_id, "paragraph_id": para_id, "sentence_id": sent_id_counter,
                "url": doc["url"], "org_name": doc["org_name"],
                "source_category": doc["source_category"], "hypothesis_tag": doc["hypothesis_tag"],
                "sentence": sentence
            })
            sent_id_counter += 1
    doc["sentence_count"] = sent_id_counter

datapoints_df = pd.DataFrame(datapoint_rows)     # sentence-level (primary datapoint unit)
paragraphs_df = pd.DataFrame(paragraph_rows)     # paragraph-level (for co-occurrence)
total_datapoints = len(datapoints_df)

print("=" * 65)
print("CORPUS SIZE (informational)")
print("=" * 65)
print(f"Documents:   {len(cleaned_documents)}  (reference: >= {DOCUMENT_REFERENCE_POINT})")
print(f"Datapoints (sentences): {total_datapoints:,}  (reference: >= {DATAPOINT_REFERENCE_POINT:,})")
print(f"Paragraphs: {len(paragraphs_df):,}")
print("=" * 65)

if total_datapoints < DATAPOINT_REFERENCE_POINT or len(cleaned_documents) < DOCUMENT_REFERENCE_POINT:
    print(f"\nTo scrape more documents/datapoints: add more rows to VERIFIED_SOURCES / LISTING_PAGES in "
          f"Section 3, or loosen RELEVANCE_TERMS, then re-run from Section 4.")

datapoints_df.to_csv("outputs/datapoints.csv", index=False)
paragraphs_df.to_csv("outputs/paragraphs.csv", index=False)
print(f"\nSaved outputs/datapoints.csv ({total_datapoints:,} sentence rows)")
print(f"Saved outputs/paragraphs.csv ({len(paragraphs_df):,} paragraph rows)")

"""## 9. Keyword tagging & document-level filtering

Per the methodology: *"Documents are retained if they contain terms from at
least two of the three keyword sets... Documents containing terms from all
three keyword sets form the primary analytical focus... two keyword sets
provide comparative and contextual evidence."*

Tags every document, sentence (datapoint), and paragraph for the three theme
sets, **then filters the document-level corpus** to keep only documents
matching >=2 sets - classified `primary` (3/3) or `comparative` (2/3).
Excluded documents are logged, not silently dropped.
"""

ai_sc_keywords = [
    "ai supply chain", "artificial intelligence supply chain",
    "machine learning logistics", "predictive analytics procurement",
    "ai demand forecasting", "ai inventory management", "ai supplier risk",
    "intelligent supply chain"
]

sc_resilience_keywords = [
    "supply chain resilience", "supply chain disruption", "supply chain agility",
    "supply chain visibility", "supply chain flexibility", "supply chain redundancy",
    "supply chain recovery", "resilient supply chain"
]

industry5_keywords = [
    "industry 5.0 supply chain", "industry 5.0 manufacturing",
    "human-centric supply chain", "sustainable supply chain",
    "resilience-by-design", "human-robot collaboration supply chain"
]

KEYWORD_SETS = {
    "ai_in_supply_chain": ai_sc_keywords,
    "supply_chain_resilience": sc_resilience_keywords,
    "industry_5_0": industry5_keywords,
}

# ------------------------------------------------------------
# Matching: check that a keyword's core words are all present in
# the text (any order, any position, simple plurals allowed)
# instead of requiring the exact contiguous phrase. An exact
# match rarely fires on real prose - e.g. "AI demand forecasting"
# vs. how people actually write "AI-driven demand forecasting".
# ------------------------------------------------------------
_STOPWORDS = {"in", "for", "the", "of", "and", "to", "a", "an", "on", "with"}


def _term_tokens(term):
    normalized = term.lower().replace("-", " ")
    tokens = re.findall(r"[a-z0-9][a-z0-9\.]*", normalized)
    return [t for t in tokens if t not in _STOPWORDS]


def _term_present(text_lower, term):
    return all(
        re.search(r"\b" + re.escape(tok) + r"s?\b", text_lower)
        for tok in _term_tokens(term)
    )


def count_keyword_mentions(text, keywords):
    text_lower = text.lower()
    return sum(1 for kw in keywords if _term_present(text_lower, kw))


def has_keywords(text, keywords):
    text_lower = text.lower()
    return any(_term_present(text_lower, kw) for kw in keywords)

# Document-level tagging
for doc in cleaned_documents:
    doc["ai_count"] = count_keyword_mentions(doc["clean_text"], ai_sc_keywords)
    doc["res_count"] = count_keyword_mentions(doc["clean_text"], sc_resilience_keywords)
    doc["i5_count"] = count_keyword_mentions(doc["clean_text"], industry5_keywords)
    doc["has_ai_sc"] = doc["ai_count"] > 0
    doc["has_sc_res"] = doc["res_count"] > 0
    doc["has_i5"] = doc["i5_count"] > 0
    doc["theme_count"] = sum([doc["has_ai_sc"], doc["has_sc_res"], doc["has_i5"]])
    if doc["theme_count"] == 3:
        doc["classification"] = "primary"
    elif doc["theme_count"] == 2:
        doc["classification"] = "comparative"
    else:
        doc["classification"] = "excluded"

all_tagged_df = pd.DataFrame(cleaned_documents)
all_tagged_df["word_count"] = all_tagged_df["clean_text"].apply(lambda t: len(t.split()))

print("Document-level theme coverage (before filtering):")
print(f"  Documents with >=1 theme: {(all_tagged_df['theme_count'] >= 1).sum()}")
print(f"  Documents with >=2 themes: {(all_tagged_df['theme_count'] >= 2).sum()}")
print(f"  Documents with all 3 themes: {(all_tagged_df['theme_count'] == 3).sum()}")

# ------------------------------------------------------------
# Apply the methodology's retention rule: keep only documents
# with >=2 of 3 keyword sets matched.
# every later section (preprocessing, topic modelling, sentiment,
# co-occurrence) uses.
# ------------------------------------------------------------
corpus_df = all_tagged_df[all_tagged_df["classification"] != "excluded"].reset_index(drop=True)
excluded_df = all_tagged_df[all_tagged_df["classification"] == "excluded"].reset_index(drop=True)

print("=" * 65)
print("DOCUMENT-LEVEL KEYWORD FILTERING")
print("=" * 65)
print(f"Documents before filtering: {len(all_tagged_df)}")
print(f"  Primary (3/3 keyword sets)     : {(corpus_df['classification'] == 'primary').sum()}")
print(f"  Comparative (2/3 keyword sets) : {(corpus_df['classification'] == 'comparative').sum()}")
print(f"  Excluded (0-1 keyword sets)    : {len(excluded_df)}")
print(f"Final corpus (>=2 sets matched): {len(corpus_df)}  (target: >= {MIN_DOCUMENTS})")

if len(excluded_df):
    excluded_df[["url", "org_name", "ai_count", "res_count", "i5_count"]] \
        .to_csv("outputs/excluded_documents_log.csv", index=False)
    print(f"\nSaved outputs/excluded_documents_log.csv ({len(excluded_df)} documents "
          f"dropped for matching fewer than 2 keyword sets)")

# Keep only datapoints/paragraphs belonging to a retained document
retained_urls = set(corpus_df["url"])
datapoints_df = datapoints_df[datapoints_df["url"].isin(retained_urls)].reset_index(drop=True)
paragraphs_df = paragraphs_df[paragraphs_df["url"].isin(retained_urls)].reset_index(drop=True)

# Sentence/paragraph-level tagging (used by co-occurrence, Section 13)
datapoints_df["has_ai_sc"] = datapoints_df["sentence"].apply(lambda s: has_keywords(s, ai_sc_keywords))
datapoints_df["has_sc_res"] = datapoints_df["sentence"].apply(lambda s: has_keywords(s, sc_resilience_keywords))
datapoints_df["has_i5"] = datapoints_df["sentence"].apply(lambda s: has_keywords(s, industry5_keywords))

paragraphs_df["has_ai_sc"] = paragraphs_df["paragraph"].apply(lambda p: has_keywords(p, ai_sc_keywords))
paragraphs_df["has_sc_res"] = paragraphs_df["paragraph"].apply(lambda p: has_keywords(p, sc_resilience_keywords))
paragraphs_df["has_i5"] = paragraphs_df["paragraph"].apply(lambda p: has_keywords(p, industry5_keywords))

print(f"\nDatapoints after filtering to retained documents: {len(datapoints_df):,}  "
      f"(target: >= {MIN_DATAPOINTS:,})")
print(f"Paragraphs after filtering: {len(paragraphs_df):,}")
print(f"\nDatapoint-level theme coverage:")
print(f"  Mention AI in SC:       {datapoints_df['has_ai_sc'].sum():,}")
print(f"  Mention SC Resilience:  {datapoints_df['has_sc_res'].sum():,}")
print(f"  Mention Industry 5.0:   {datapoints_df['has_i5'].sum():,}")

"""## 10. Preprocessing (spaCy)

Per the methodology: *"lowercase, removing special characters and
punctuation, tokenisation, lemmatisation... stop words and tokens of fewer
than three characters removed."* Produces `lemmatised_text`, used as the
input to topic modelling in Section 11.
"""

import spacy

nlp = spacy.load("en_core_web_sm", disable=["ner", "parser"])
nlp.max_length = 2_000_000

def preprocess_spacy(text):
    text = text.lower()
    text = re.sub(r"[^a-z\s]", " ", text)   # strip punctuation/special chars, keep letters
    doc = nlp(text)
    lemmas = [
        tok.lemma_ for tok in doc
        if not tok.is_stop and not tok.is_space and len(tok.lemma_) >= 3
    ]
    return " ".join(lemmas)

print(f"Preprocessing {len(corpus_df)} documents with spaCy "
      f"(lowercase, de-punctuate, tokenise, lemmatise, remove stopwords/short tokens)...")
print("This may take a minute or two for a corpus this size.")

corpus_df["lemmatised_text"] = corpus_df["clean_text"].apply(preprocess_spacy)
corpus_df["lemma_word_count"] = corpus_df["lemmatised_text"].apply(lambda t: len(t.split()))

print(f"Done. Mean lemmatised length: {corpus_df['lemma_word_count'].mean():.0f} words/doc "
      f"(from mean {corpus_df['word_count'].mean():.0f} words/doc before preprocessing).")

"""## 11. Topic modelling (BERTopic)

Per the methodology: BERTopic uses sentence-level embeddings rather than raw
word frequencies to group documents into semantically coherent clusters.
Examines whether AI-related documents sit centrally in the same topic
clusters as supply chain resilience and Industry 5.0 documents - evidence for
**H2**.
"""

from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP
from hdbscan import HDBSCAN


# min_topic_size scales with corpus size but stays low enough to let BERTopic
# find several distinct clusters instead of one dominant one - too high a value
# relative to corpus size is the second most common cause of "too few topics"
min_topic_size = max(2, min(8, len(corpus_df) // 20))

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# Truncate to a reasonable length for embedding - very long documents dilute
# sentence embeddings; the first ~500 words usually carry the core topic signal
embed_texts = corpus_df["clean_text"].apply(lambda t: " ".join(t.split()[:500])).tolist()
print(f"Computing embeddings for {len(embed_texts)} documents...")
doc_embeddings = embedding_model.encode(embed_texts, show_progress_bar=False)

# Explicit UMAP/HDBSCAN tuned for a small-to-medium corpus - the BERTopic
# defaults (n_neighbors=15) assume larger corpora and over-smooth small ones
# into a single cluster.
umap_model = UMAP(n_neighbors=min(10, max(2, len(corpus_df) - 1)), n_components=5,
                   min_dist=0.0, metric="cosine", random_state=42)
hdbscan_model = HDBSCAN(min_cluster_size=min_topic_size, min_samples=1,
                         metric="euclidean", cluster_selection_method="eom",
                         prediction_data=True)
vectorizer_model = CountVectorizer(stop_words="english", ngram_range=(1, 2), min_df=2)

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    min_topic_size=min_topic_size,
    calculate_probabilities=False,
    verbose=False,
)

docs_for_topics = corpus_df["lemmatised_text"].tolist()  # used for keyword extraction only

# Guard against a degenerate case (rare, but seen when a corpus's lemmatised
# vocabulary is unusually sparse/repetitive): the c-TF-IDF step can throw a
# scipy error if min_df=2 leaves too few surviving terms. If it does, retry
# once with a looser vectorizer instead of crashing the whole pipeline.
try:
    topics, _ = topic_model.fit_transform(docs_for_topics, embeddings=doc_embeddings)
except (ValueError, TypeError) as e:
    print(f"Topic modelling failed with default settings ({e}).")
    print("Retrying with a looser vectorizer (min_df=1, unigrams only)...")
    vectorizer_model = CountVectorizer(stop_words="english", ngram_range=(1, 1), min_df=1)
    topic_model = BERTopic(
        embedding_model=embedding_model, umap_model=umap_model, hdbscan_model=hdbscan_model,
        vectorizer_model=vectorizer_model, min_topic_size=min_topic_size,
        calculate_probabilities=False, verbose=False,
    )
    topics, _ = topic_model.fit_transform(docs_for_topics, embeddings=doc_embeddings)

corpus_df["topic"] = topics

topic_info = topic_model.get_topic_info()
topic_info.to_csv("outputs/topic_info.csv", index=False)

n_topics = (topic_info["Topic"] != -1).sum()
print(f"BERTopic found {n_topics} topics "
      f"({(corpus_df['topic'] == -1).sum()} documents unassigned as outliers).")
print("\nTop topics by size:")
print(topic_info[topic_info["Topic"] != -1].head(15)[["Topic", "Count", "Name"]].to_string(index=False))

if n_topics <= 2:
    print("\n  Still finding very few topics. Likely causes to check next:")
    print("  - Corpus may be too small/homogeneous for this many expected themes")
    print("  - Try lowering min_topic_size further (edit the line above)")
    print("  - Try nr_topics=None (already default) vs setting a fixed target, e.g. nr_topics=8")

"""### Topic keyword summary

A clean, report-ready table: topic ID, document count, and its top 10 keywords -
this is what you'd cite when describing "the topics BERTopic identified"
(e.g. AI adoption, demand forecasting, risk/disruption management, etc.).
"""

topic_keyword_rows = []
for topic_id in topic_info[topic_info["Topic"] != -1]["Topic"]:
    words = topic_model.get_topic(topic_id)
    top_keywords = ", ".join(w for w, _ in words[:10])
    count = topic_info.loc[topic_info["Topic"] == topic_id, "Count"].values[0]
    topic_keyword_rows.append({"Topic": topic_id, "Document Count": count, "Top Keywords": top_keywords})

topic_keyword_summary = pd.DataFrame(topic_keyword_rows).sort_values("Document Count", ascending=False)
topic_keyword_summary.to_csv("outputs/topic_keyword_summary.csv", index=False)

print("TOPIC KEYWORD SUMMARY")
print("=" * 65)
for _, row in topic_keyword_summary.iterrows():
    print(f"Topic {row['Topic']} ({row['Document Count']} docs): {row['Top Keywords']}")
print("\nSaved outputs/topic_keyword_summary.csv")

"""### Representative paragraph per topic

For each topic, the single paragraph (from the original, non-lemmatised text)
that best matches that topic's top keywords - gives a readable example of what
each topic is actually about, not just a keyword list.
"""

def best_paragraph_for_topic(topic_id, topic_urls):
    """Find the paragraph (within this topic's documents) containing the most
    of that topic's top keywords - a simple, fast proxy for 'most representative'."""
    top_words = [w for w, _ in topic_model.get_topic(topic_id)[:10]]
    candidates = paragraphs_df[paragraphs_df["url"].isin(topic_urls)]
    if candidates.empty:
        return None
    scores = candidates["paragraph"].apply(lambda p: sum(1 for w in top_words if w in p.lower()))
    if scores.max() == 0:
        return None
    return candidates.loc[scores.idxmax(), "paragraph"]


print("REPRESENTATIVE PARAGRAPH PER TOPIC")
print("=" * 65)
representative_rows = []
for topic_id in topic_info[topic_info["Topic"] != -1]["Topic"].head(10):
    topic_urls = corpus_df.loc[corpus_df["topic"] == topic_id, "url"]
    para = best_paragraph_for_topic(topic_id, topic_urls)
    representative_rows.append({"Topic": topic_id, "Representative Paragraph": para or "(none found)"})
    print(f"\n--- Topic {topic_id} ---")
    print((para or "(no matching paragraph found)")[:400])

pd.DataFrame(representative_rows).to_csv("outputs/topic_representative_paragraphs.csv", index=False)
print("\n\nSaved outputs/topic_representative_paragraphs.csv")

# H2 evidence: for each topic, what share of its documents are tagged
# has_ai_sc / has_sc_res / has_i5? A topic where all three run high suggests
# AI terms are central to the same cluster as resilience/Industry 5.0 terms.
topic_theme_summary = (
    corpus_df[corpus_df["topic"] != -1]
    .groupby("topic")
    .agg(doc_count=("url", "count"),
         pct_has_ai_sc=("has_ai_sc", "mean"),
         pct_has_sc_res=("has_sc_res", "mean"),
         pct_has_i5=("has_i5", "mean"))
    .sort_values("doc_count", ascending=False)
)
topic_theme_summary[["pct_has_ai_sc", "pct_has_sc_res", "pct_has_i5"]] = \
    (topic_theme_summary[["pct_has_ai_sc", "pct_has_sc_res", "pct_has_i5"]] * 100).round(1)
topic_theme_summary.to_csv("outputs/topic_theme_centrality.csv")

print("Theme prevalence (%) within each topic - H2 evidence:")
print(topic_theme_summary.head(10).to_string())

"""## 12. Sentiment analysis (RoBERTa)

Per the methodology: each document classified positive/neutral/negative using
a pre-trained RoBERTa transformer. Documents are chunked to the model's token
limit and chunk-level probabilities averaged, since reports often exceed 512
tokens. Produces evidence for **H1** (positive sentiment in AI+resilience
co-mentions) and **H3** (sentiment difference between `primary` and
`comparative` document groups).
"""

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import torch.nn.functional as F

SENTIMENT_MODEL = "cardiffnlp/twitter-roberta-base-sentiment-latest"
sent_tokenizer = AutoTokenizer.from_pretrained(SENTIMENT_MODEL)
sent_model = AutoModelForSequenceClassification.from_pretrained(SENTIMENT_MODEL)
sent_model.eval()
SENT_LABELS = ["negative", "neutral", "positive"]  # this model's label order


def sentiment_for_text(text, max_chunk_words=350):
    """
    Chunks text to fit the model's context window, classifies EACH chunk
    independently, and takes the MAJORITY VOTE of per-chunk labels (not the
    average of softmax probabilities).

    Why majority vote instead of averaging: averaging probabilities across
    chunks systematically dilutes localized negative language. A report might
    have one paragraph on disruption/risk (negative) surrounded by neutral
    operational description - averaging softmax scores across 8 chunks pulls
    that signal toward neutral before argmax is even applied, so genuinely
    negative sections of text tend to average out to a neutral document. A
    majority vote preserves whichever sentiment is most COMMON across chunks,
    which is a more standard and defensible way to aggregate.

    Also returns:
      - max_negative_prob: the single HIGHEST negative-class probability seen
        across any chunk, and whether that chunk's argmax was actually
        "negative" (chunk_negative_dominant). This is a supplementary signal -
        even if the document's majority-vote label isn't negative, this shows
        whether meaningfully negative/risk language appears anywhere in it,
        which matters for interpreting a "zero negative documents" result.
    """
    words = text.split()
    if not words:
        return "neutral", 1 / 3, 1 / 3, 1 / 3, 0.0, False

    chunks = [" ".join(words[i:i + max_chunk_words])
              for i in range(0, len(words), max_chunk_words)]
    chunks = chunks[:8]  # cap runtime

    chunk_labels = []
    chunk_probs = []
    with torch.no_grad():
        for chunk in chunks:
            inputs = sent_tokenizer(chunk, return_tensors="pt", truncation=True, max_length=512)
            logits = sent_model(**inputs).logits[0]
            probs = F.softmax(logits, dim=0)
            chunk_labels.append(SENT_LABELS[int(probs.argmax())])
            chunk_probs.append(probs.tolist())

    # Majority vote across chunks (ties broken by mean probability)
    from collections import Counter
    vote_counts = Counter(chunk_labels)
    top_count = max(vote_counts.values())
    tied_labels = [l for l, c in vote_counts.items() if c == top_count]

    mean_probs = torch.tensor(chunk_probs).mean(dim=0).tolist()
    if len(tied_labels) == 1:
        final_label = tied_labels[0]
    else:
        final_label = SENT_LABELS[int(torch.tensor(mean_probs).argmax())]

    # Supplementary "critical language" signal
    neg_probs_per_chunk = [p[0] for p in chunk_probs]
    max_negative_prob = max(neg_probs_per_chunk)
    chunk_negative_dominant = any(l == "negative" for l in chunk_labels)

    return final_label, mean_probs[0], mean_probs[1], mean_probs[2], max_negative_prob, chunk_negative_dominant

print(f"Running sentiment analysis on {len(corpus_df)} documents "
      f"(chunked, majority-vote label + critical-language signal)...")
print("This is the slowest step in the pipeline - expect a few minutes.")
print("-" * 65)

sentiment_rows = []
for i, row in corpus_df.iterrows():
    label, neg, neu, pos, max_neg_prob, has_negative_chunk = sentiment_for_text(row["clean_text"])
    sentiment_rows.append({
        "sentiment_label": label, "sentiment_negative": neg,
        "sentiment_neutral": neu, "sentiment_positive": pos,
        "max_negative_chunk_prob": max_neg_prob,
        "has_negative_chunk": has_negative_chunk,
    })
    if (i + 1) % 25 == 0 or (i + 1) == len(corpus_df):
        print(f"  {i + 1}/{len(corpus_df)} documents scored")

sentiment_df = pd.DataFrame(sentiment_rows)
corpus_df = pd.concat([corpus_df.reset_index(drop=True), sentiment_df], axis=1)

print("-" * 65)
print("Overall sentiment distribution (document-level majority vote):")
print(corpus_df["sentiment_label"].value_counts())

print(f"\nInvestigating the 'zero negative' question:")
print(f"  Documents with >=1 chunk classified negative: "
      f"{corpus_df['has_negative_chunk'].sum()} / {len(corpus_df)} "
      f"({corpus_df['has_negative_chunk'].mean():.1%})")
print(f"  Mean max-negative-chunk probability across corpus: "
      f"{corpus_df['max_negative_chunk_prob'].mean():.3f}")
print(f"  Documents with max negative-chunk probability > 0.5: "
      f"{(corpus_df['max_negative_chunk_prob'] > 0.5).sum()}")

if corpus_df["sentiment_label"].eq("negative").sum() == 0 and corpus_df["has_negative_chunk"].sum() > 0:
    print("\n  No document's OVERALL label is negative, but some individual chunks")
    print("  were - meaning critical/risk language exists but is a MINORITY of each")
    print("  document\'s content, consistent with corporate/consulting sources that")
    print("  frame risk in solution-oriented language. Report both the document-level")
    print("  label distribution AND this chunk-level signal in your results section.")
elif corpus_df["sentiment_label"].eq("negative").sum() == 0 and corpus_df["has_negative_chunk"].sum() == 0:
    print("\n  No negative content detected at ALL, even at the chunk level. This is")
    print("  worth checking further - consider testing a small sample of documents you")
    print("  know discuss disruption/risk explicitly, to confirm the model is sensitive")
    print("  to this domain\'s language (a Twitter-tuned model may under-detect formal")
    print("  business-risk phrasing). A domain-tuned alternative (e.g. ProsusAI/finbert)")
    print("  is worth trying as a robustness check if this persists.")

# ------------------------------------------------------------
# H1 evidence (CORRECTED): a single "27.9% positive" figure with no comparison
# group isn't a hypothesis test - positive compared to what? Rebuilt as a
# proper independent-samples t-test, same structure as H3 below: positive-
# sentiment probability in documents that co-mention AI + SC Resilience vs
# documents that mention SC Resilience WITHOUT AI (the natural comparison
# group for "does AI's presence relate to more positive resilience framing").
# ------------------------------------------------------------
h1_with_ai    = corpus_df["has_ai_sc"] & corpus_df["has_sc_res"]
h1_without_ai = ~corpus_df["has_ai_sc"] & corpus_df["has_sc_res"]

h1_with_ai_scores    = corpus_df.loc[h1_with_ai, "sentiment_positive"]
h1_without_ai_scores = corpus_df.loc[h1_without_ai, "sentiment_positive"]

print("H1 EVIDENCE (complementary) - sentiment comparison: SC Resilience WITH AI mentions")
print("             vs SC Resilience WITHOUT AI mentions")
print("-" * 65)
print(f"With AI mentions:    n={len(h1_with_ai_scores)}, "
      f"mean positive-prob={h1_with_ai_scores.mean():.3f}" if len(h1_with_ai_scores) else "With AI mentions: n=0")
print(f"Without AI mentions: n={len(h1_without_ai_scores)}, "
      f"mean positive-prob={h1_without_ai_scores.mean():.3f}" if len(h1_without_ai_scores) else "Without AI mentions: n=0")

if len(h1_with_ai_scores) >= 2 and len(h1_without_ai_scores) >= 2:
    h1_t_stat, h1_p_val = stats.ttest_ind(h1_with_ai_scores, h1_without_ai_scores, equal_var=False)
    h1_sig = "significant (p<0.05)" if h1_p_val < 0.05 else "not significant (p>=0.05)"
    print(f"\nIndependent t-test: t={h1_t_stat:.3f}, p={h1_p_val:.4f} -> {h1_sig}")
    h1_ttest_result = {"t_statistic": round(h1_t_stat, 3), "p_value": round(h1_p_val, 4),
                        "n_with_ai": len(h1_with_ai_scores), "n_without_ai": len(h1_without_ai_scores),
                        "significant": h1_p_val < 0.05}
else:
    print("\nToo few documents in one or both groups for a reliable t-test.")
    h1_ttest_result = {"t_statistic": None, "p_value": None,
                        "n_with_ai": len(h1_with_ai_scores), "n_without_ai": len(h1_without_ai_scores),
                        "significant": None}

# Kept for reference/appendix only - NOT used as primary evidence in the summary
# table below, since a single percentage with no comparison group isn't a test.
co_mention_mask = corpus_df["has_ai_sc"] & corpus_df["has_sc_res"]
co_mention_docs = corpus_df[co_mention_mask]
h1_positive_share = (co_mention_docs["sentiment_label"] == "positive").mean() if len(co_mention_docs) else float("nan")

# ------------------------------------------------------------
# H3 evidence: independent-samples t-test comparing positive-sentiment
# probability between two SPECIFIC groups, per the methodology's exact
# wording: "documents addressing AI and supply chain resilience WITHIN
# an Industry 5.0 context" vs "those treating AI, supply chain resilience
# INDEPENDENTLY of Industry 5.0 principles". Both groups must still
# address AI and SC resilience - the only difference is Industry 5.0
# framing. This is narrower than the generic primary/comparative
# (3-theme/2-theme) split: a document tagged "comparative" only because
# it matches SC-Resilience + Industry5.0 (no AI) would NOT belong in
# either group here, since it isn't about AI at all.
# ------------------------------------------------------------
h3_with_i5    = corpus_df["has_ai_sc"] & corpus_df["has_sc_res"] & corpus_df["has_i5"]
h3_without_i5 = corpus_df["has_ai_sc"] & corpus_df["has_sc_res"] & ~corpus_df["has_i5"]

primary_scores     = corpus_df.loc[h3_with_i5, "sentiment_positive"]
comparative_scores = corpus_df.loc[h3_without_i5, "sentiment_positive"]

print("H3 EVIDENCE - sentiment comparison: AI+SCResilience WITH Industry 5.0 framing")
print("             vs AI+SCResilience WITHOUT Industry 5.0 framing")
print("-" * 65)
print(f"With Industry 5.0 framing:    n={len(primary_scores)}, "
      f"mean positive-prob={primary_scores.mean():.3f}" if len(primary_scores) else "With Industry 5.0 framing: n=0")
print(f"Without Industry 5.0 framing: n={len(comparative_scores)}, "
      f"mean positive-prob={comparative_scores.mean():.3f}" if len(comparative_scores) else "Without Industry 5.0 framing: n=0")

if len(primary_scores) >= 2 and len(comparative_scores) >= 2:
    t_stat, p_val = stats.ttest_ind(primary_scores, comparative_scores, equal_var=False)
    sig = "significant (p<0.05)" if p_val < 0.05 else "not significant (p>=0.05)"
    print(f"\nIndependent t-test: t={t_stat:.3f}, p={p_val:.4f} -> {sig}")
    h3_ttest_result = {"t_statistic": round(t_stat, 3), "p_value": round(p_val, 4),
                        "n_primary": len(primary_scores), "n_comparative": len(comparative_scores),
                        "significant": p_val < 0.05}
else:
    print("\nToo few documents in one or both groups for a reliable t-test "
          "(need >=2 per group at minimum, realistically >=10-15 for a "
          "defensible result). Add more sources so both groups grow.")
    h3_ttest_result = {"t_statistic": None, "p_value": None,
                        "n_primary": len(primary_scores), "n_comparative": len(comparative_scores),
                        "significant": None}

"""## 13. Co-occurrence analysis

Per the methodology: tests whether AI, supply chain resilience, and
Industry 5.0 terms appear together significantly more than chance, at four
levels of strictness (document, sentence, paragraph, 3-sentence window).
"""

def cooccurrence_stats(df, v1, v2, label, level_name, unit_col_name):
    both = (df[v1] & df[v2]).sum()
    either = (df[v1] | df[v2]).sum()
    jaccard = both / either if either > 0 else 0
    phi, p = stats.pearsonr(df[v1].astype(int), df[v2].astype(int))
    sig = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else "n.s."
    print(f"  {label:<45} co-occur in {both} {unit_col_name}, "
          f"Jaccard={jaccard:.3f}, phi={phi:.3f} {sig}")
    return {
        "Comparison": label, "Level": level_name,
        f"co_occurring_{unit_col_name}": int(both), "jaccard": round(jaccard, 3),
        "phi_coefficient": round(phi, 3), "p_value": round(p, 3), "Significance": sig
    }


THEME_PAIRS = [
    ("has_ai_sc", "has_sc_res", "AI in SC & SC Resilience"),
    ("has_ai_sc", "has_i5", "AI in SC & Industry 5.0"),
    ("has_sc_res", "has_i5", "SC Resilience & Industry 5.0"),
]

# --- Level 1: Document-level (keyword-count correlation) ---
print("LEVEL 1 - DOCUMENT-LEVEL CO-OCCURRENCE (keyword-count correlation)")
print("-" * 65)

count_pairs = [
    ("ai_count", "res_count", "AI in SC vs SC Resilience"),
    ("ai_count", "i5_count", "AI in SC vs Industry 5.0"),
    ("res_count", "i5_count", "SC Resilience vs Industry 5.0"),
]

doc_cooc_results = []
for v1, v2, label in count_pairs:
    valid = corpus_df[[v1, v2]].dropna()
    if len(valid) > 2:
        r, p = stats.pearsonr(valid[v1], valid[v2])
        sig = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else "n.s."
        print(f"  {label:<32} r={r:.3f}, p={p:.3f} {sig}")
        doc_cooc_results.append({"Comparison": label, "Level": "Document", "r": round(r, 3), "p_value": round(p, 3), "Significance": sig})

# --- Level 2: Sentence-level (strictest - same exact sentence) ---
print("\nLEVEL 2 - SENTENCE-LEVEL CO-OCCURRENCE (same sentence, strictest)")
print("-" * 65)
sentence_cooc_results = [
    cooccurrence_stats(datapoints_df, v1, v2, f"{label} (same sentence)", "Sentence", "sentences")
    for v1, v2, label in THEME_PAIRS
]

# --- Level 3: Paragraph-level (looser - same paragraph) ---
print("\nLEVEL 3 - PARAGRAPH-LEVEL CO-OCCURRENCE (same paragraph)")
print("-" * 65)
paragraph_cooc_results = [
    cooccurrence_stats(paragraphs_df, v1, v2, f"{label} (same paragraph)", "Paragraph", "paragraphs")
    for v1, v2, label in THEME_PAIRS
]

# --- Level 4: Sliding sentence window (middle ground, doesn't need paragraph structure) ---
print("\nLEVEL 4 - SLIDING WINDOW CO-OCCURRENCE (within 3 consecutive sentences)")
print("-" * 65)

WINDOW_SIZE = 3
window_rows = []
for doc_id, doc_sentences in datapoints_df.groupby("doc_id"):
    doc_sentences = doc_sentences.sort_values("sentence_id").reset_index(drop=True)
    for i in range(len(doc_sentences)):
        window = doc_sentences.iloc[i:i + WINDOW_SIZE]
        window_rows.append({
            "doc_id": doc_id, "window_start": i,
            "has_ai_sc": window["has_ai_sc"].any(),
            "has_sc_res": window["has_sc_res"].any(),
            "has_i5": window["has_i5"].any(),
        })
windows_df = pd.DataFrame(window_rows)

window_cooc_results = [
    cooccurrence_stats(windows_df, v1, v2, f"{label} (3-sentence window)", "Sliding window (3 sentences)", "windows")
    for v1, v2, label in THEME_PAIRS
]

# --- Save everything ---
cooc_results_df = pd.DataFrame(
    doc_cooc_results + sentence_cooc_results + paragraph_cooc_results + window_cooc_results
)
cooc_results_df.to_excel("outputs/cooccurrence_results.xlsx", index=False)
paragraphs_df.to_csv("outputs/paragraphs.csv", index=False)
print("\nSaved outputs/cooccurrence_results.xlsx (all 4 levels)")

# Visualise all 4 co-occurrence levels
fig, axes = plt.subplots(1, 4, figsize=(22, 5))
theme_labels = ["AI in SC", "SC Resilience", "Industry 5.0"]

doc_corr = corpus_df[["ai_count", "res_count", "i5_count"]].corr()
doc_corr.index = doc_corr.columns = theme_labels
sns.heatmap(doc_corr, annot=True, fmt=".3f", cmap="Blues", vmin=0, vmax=1,
            linewidths=0.5, linecolor="white", ax=axes[0], cbar_kws={"shrink": 0.7})
axes[0].set_title("1. Document-level\n(keyword-count correlation)")

sent_corr = datapoints_df[["has_ai_sc", "has_sc_res", "has_i5"]].astype(int).corr()
sent_corr.index = sent_corr.columns = theme_labels
sns.heatmap(sent_corr, annot=True, fmt=".3f", cmap="Greens", vmin=0, vmax=1,
            linewidths=0.5, linecolor="white", ax=axes[1], cbar_kws={"shrink": 0.7})
axes[1].set_title("2. Sentence-level\n(same sentence, strictest)")

para_corr = paragraphs_df[["has_ai_sc", "has_sc_res", "has_i5"]].astype(int).corr()
para_corr.index = para_corr.columns = theme_labels
sns.heatmap(para_corr, annot=True, fmt=".3f", cmap="Oranges", vmin=0, vmax=1,
            linewidths=0.5, linecolor="white", ax=axes[2], cbar_kws={"shrink": 0.7})
axes[2].set_title("3. Paragraph-level\n(same paragraph)")

window_corr = windows_df[["has_ai_sc", "has_sc_res", "has_i5"]].astype(int).corr()
window_corr.index = window_corr.columns = theme_labels
sns.heatmap(window_corr, annot=True, fmt=".3f", cmap="Purples", vmin=0, vmax=1,
            linewidths=0.5, linecolor="white", ax=axes[3], cbar_kws={"shrink": 0.7})
axes[3].set_title(f"4. Sliding window\n({WINDOW_SIZE}-sentence window)")

plt.tight_layout()
plt.savefig("outputs/charts/cooccurrence_matrices.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved outputs/charts/cooccurrence_matrices.png (all 4 levels)")

"""## 14. NLP-Based Hypothesis Evidence and Triangulation

Separates **primary statistical tests** (correlation/t-test, with p-values) from
**complementary/descriptive evidence** (topic-modelling patterns, which partly
reflect the corpus's own keyword-based filtering criteria and so are reported
as supporting context, not independent confirmatory tests).

This is the NLP strand's contribution only - per the methodology's triangulation
design, these results should be read alongside the survey strand's hierarchical
regression (H1, H3) and Pearson correlation (H2) results from the separate
survey analysis notebook.
"""

def interpret(p_value, alpha=0.05):
    if p_value is None:
        return "Insufficient data"
    return "Supporting textual evidence" if p_value < alpha else "No significant textual evidence"


h1_cooc = next((row for row in doc_cooc_results if row["Comparison"] == "AI in SC vs SC Resilience"), None)
h2_cooc = next((row for row in doc_cooc_results if row["Comparison"] == "AI in SC vs Industry 5.0"), None)

h2_topics_all_three = int(((topic_theme_summary["pct_has_ai_sc"] > 50) &
                            (topic_theme_summary["pct_has_sc_res"] > 50) &
                            (topic_theme_summary["pct_has_i5"] > 50)).sum())
h2_topic_result_str = f"{h2_topics_all_three} of {len(topic_theme_summary)} topics show >50% prevalence on all 3 themes"

hypothesis_summary_rows = [
    # --- Primary statistical tests (the numbers that actually carry inferential weight) ---
    {
        "Hypothesis": "H1", "NLP analysis": "Document-level AI-Resilience correlation",
        "Result": f"r={h1_cooc['r']}, p={h1_cooc['p_value']}" if h1_cooc else "N/A",
        "Interpretation": interpret(h1_cooc["p_value"] if h1_cooc else None),
        "Evidence tier": "Primary", "N": len(corpus_df),
    },
    {
        "Hypothesis": "H2", "NLP analysis": "AI-Industry 5.0 correlation",
        "Result": f"r={h2_cooc['r']}, p={h2_cooc['p_value']}" if h2_cooc else "N/A",
        "Interpretation": interpret(h2_cooc["p_value"] if h2_cooc else None),
        "Evidence tier": "Primary", "N": len(corpus_df),
    },
    {
        "Hypothesis": "H3", "NLP analysis": "Sentiment comparison (t-test)",
        "Result": (f"t={h3_ttest_result['t_statistic']}, p={h3_ttest_result['p_value']}"
                   if h3_ttest_result["p_value"] is not None else "Insufficient data"),
        "Interpretation": interpret(h3_ttest_result["p_value"]),
        "Evidence tier": "Primary",
        "N": f"with_i5={h3_ttest_result['n_primary']}, without_i5={h3_ttest_result['n_comparative']}",
    },
    # --- Complementary / descriptive evidence (not primary confirmatory tests) ---
    {
        "Hypothesis": "H1", "NLP analysis": "Sentiment comparison (t-test): SC Resilience with vs without AI mentions",
        "Result": (f"t={h1_ttest_result['t_statistic']}, p={h1_ttest_result['p_value']}"
                   if h1_ttest_result["p_value"] is not None else "Insufficient data"),
        "Interpretation": interpret(h1_ttest_result["p_value"]) + " (complementary)",
        "Evidence tier": "Complementary evidence only",
        "N": f"with_ai={h1_ttest_result['n_with_ai']}, without_ai={h1_ttest_result['n_without_ai']}",
    },
    {
        "Hypothesis": "H2", "NLP analysis": "Topic/co-occurrence analysis",
        "Result": h2_topic_result_str,
        "Interpretation": "Complementary evidence only",
        "Evidence tier": "Complementary evidence only",
        "N": len(topic_theme_summary),
    },
]

hypothesis_summary_df = pd.DataFrame(hypothesis_summary_rows)
hypothesis_summary_df.to_csv("outputs/hypothesis_summary.csv", index=False)

print("=" * 100)
print("NLP-BASED HYPOTHESIS EVIDENCE AND TRIANGULATION")
print("=" * 100)
print(hypothesis_summary_df[["Hypothesis", "NLP analysis", "Result", "Interpretation", "Evidence tier", "N"]].to_string(index=False))
print()
print("Saved outputs/hypothesis_summary.csv")
print()
print("Note on 'Complementary evidence only' rows: the topic-modelling centrality")
print("metric is partly circular, since the corpus was already filtered to retain")
print(">=2-of-3-theme documents before topic modelling ran - high theme prevalence")
print("within topics is therefore expected, not a fully independent discovery. It is")
print("reported as descriptive/contextual support, not a confirmatory statistical test.")
print()
print("Note: this is the NLP strand's evidence only. Per the methodology's")
print("triangulation design, these results should be read alongside the survey")
print("strand's hierarchical regression (H1, H3) and Pearson correlation (H2)")
print("results from the separate survey analysis notebook.")

"""## 15. Visualisations & descriptive statistics"""

print("=" * 65)
print("DESCRIPTIVE STATISTICS")
print("=" * 65)

desc_stats = {
    "Total documents (retained)": len(corpus_df),
    "  - Primary (3/3 themes)": (corpus_df["classification"] == "primary").sum(),
    "  - Comparative (2/3 themes)": (corpus_df["classification"] == "comparative").sum(),
    "Documents excluded (<2 themes)": len(excluded_df),
    "Total datapoints (sentences)": len(datapoints_df),
    "Total paragraphs": len(paragraphs_df),
    "Mean words/document": round(corpus_df["word_count"].mean(), 1),
    "Median words/document": int(corpus_df["word_count"].median()),
    "Mean lemmatised words/document": round(corpus_df["lemma_word_count"].mean(), 1),
    "Mean sentences (datapoints)/document": round(len(datapoints_df) / max(len(corpus_df), 1), 1),
    "Mean paragraphs/document": round(len(paragraphs_df) / max(len(corpus_df), 1), 1),
    "Topics found (BERTopic)": n_topics,
    "Documents with >=1 negative-sentiment chunk": int(corpus_df["has_negative_chunk"].sum()),
}
desc_stats_df = pd.DataFrame(list(desc_stats.items()), columns=["Metric", "Value"])
desc_stats_df.to_csv("outputs/descriptive_statistics.csv", index=False)
print(desc_stats_df.to_string(index=False))

print("\nDocuments by source category:")
print(corpus_df["source_category"].value_counts())
print("\nDocuments by classification:")
print(corpus_df["classification"].value_counts())
print("\nSentiment distribution:")
print(corpus_df["sentiment_label"].value_counts())

"""### Individual charts

Each visualisation below is its own cell/figure (rather than one crowded 6-panel
grid) so each can be exported, resized, or dropped into the dissertation
individually.
"""

fig, ax = plt.subplots(figsize=(9, 5))
corpus_df["source_category"].value_counts().plot(kind="barh", ax=ax, color="#4C72B0")
ax.set_title("Documents by Source Category")
ax.set_xlabel("Count")
ax.invert_yaxis()
plt.tight_layout()
plt.savefig("outputs/charts/01_documents_by_category.png", dpi=150, bbox_inches="tight")
plt.show()

fig, ax = plt.subplots(figsize=(7, 5))
theme_coverage = pd.Series({
    ">=1 theme": (corpus_df["theme_count"] >= 1).sum(),
    ">=2 themes (retained)": (corpus_df["theme_count"] >= 2).sum(),
    "All 3 themes (primary)": (corpus_df["theme_count"] == 3).sum(),
})
theme_coverage.plot(kind="bar", ax=ax, color="#55A868")
ax.set_title("Document-Level Theme Coverage")
ax.set_ylabel("Documents")
ax.tick_params(axis="x", rotation=20)
plt.tight_layout()
plt.savefig("outputs/charts/02_theme_coverage.png", dpi=150, bbox_inches="tight")
plt.show()

fig, ax = plt.subplots(figsize=(7, 7))
classification_counts = pd.concat([
    corpus_df["classification"], pd.Series(["excluded"] * len(excluded_df))
]).value_counts()
classification_counts.plot(kind="pie", ax=ax, autopct="%1.0f%%",
                            colors=["#4C72B0", "#DD8452", "#C44E52"])
ax.set_title("Document Classification")
ax.set_ylabel("")
plt.tight_layout()
plt.savefig("outputs/charts/03_document_classification.png", dpi=150, bbox_inches="tight")
plt.show()

fig, ax = plt.subplots(figsize=(7, 5))
corpus_df["sentiment_label"].value_counts().reindex(["positive", "neutral", "negative"]).plot(
    kind="bar", ax=ax, color=["#55A868", "#DD8452", "#C44E52"])
ax.set_title("Sentiment Distribution (Document-Level, Majority Vote)")
ax.set_ylabel("Documents")
ax.tick_params(axis="x", rotation=0)
plt.tight_layout()
plt.savefig("outputs/charts/04_sentiment_distribution.png", dpi=150, bbox_inches="tight")
plt.show()

# Supplementary: chunk-level critical-language signal (see Section 12 investigation)
fig, ax = plt.subplots(figsize=(7, 5))
ax.hist(corpus_df["max_negative_chunk_prob"], bins=20, color="#C44E52", edgecolor="white")
ax.set_title("Max Negative-Chunk Probability per Document\n(supplementary - shows critical language even if not the modal label)")
ax.set_xlabel("Max P(negative) across any chunk in the document")
ax.set_ylabel("Documents")
plt.tight_layout()
plt.savefig("outputs/charts/04b_max_negative_chunk_distribution.png", dpi=150, bbox_inches="tight")
plt.show()

fig, ax = plt.subplots(figsize=(7, 5))
sentiment_by_group = corpus_df[corpus_df["classification"].isin(["primary", "comparative"])]
sns.boxplot(data=sentiment_by_group, x="classification", y="sentiment_positive", ax=ax,
            order=["comparative", "primary"], palette=["#DD8452", "#4C72B0"])
ax.set_title("Positive-Sentiment Probability by Group (H3)")
ax.set_xlabel("")
ax.set_ylabel("P(positive)")
plt.tight_layout()
plt.savefig("outputs/charts/05_sentiment_by_group_h3.png", dpi=150, bbox_inches="tight")
plt.show()

fig, ax = plt.subplots(figsize=(8, 5))
ax.hist(corpus_df["word_count"], bins=25, color="#8172B2", edgecolor="white")
ax.set_title("Document Length Distribution")
ax.set_xlabel("Words per document")
ax.set_ylabel("Documents")
plt.tight_layout()
plt.savefig("outputs/charts/06_document_length.png", dpi=150, bbox_inches="tight")
plt.show()

"""### Word clouds

Corpus-wide, plus one per document group (primary/comparative) so you can see
whether the dominant vocabulary actually differs between groups - useful
qualitative support alongside the keyword-count statistics.
"""

from wordcloud import WordCloud

def make_wordcloud(text, title, filename):
    if len(text.strip()) < 50:
        print(f"Not enough text for wordcloud: {title}")
        return
    wc = WordCloud(width=1200, height=600, background_color="white", colormap="Blues",
                    max_words=100, collocations=False).generate(text)
    plt.figure(figsize=(14, 7))
    plt.imshow(wc, interpolation="bilinear")
    plt.axis("off")
    plt.title(title, fontsize=13, pad=15)
    plt.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches="tight")
    plt.show()

# Corpus-wide
all_text = " ".join(corpus_df["lemmatised_text"].dropna().tolist())
make_wordcloud(all_text, "Most Frequent Terms - Full Corpus", "outputs/charts/wordcloud_all.png")

# Primary (all 3 themes) vs comparative (2 themes) - qualitative check that
# vocabulary genuinely differs between these groups
primary_text = " ".join(corpus_df.loc[corpus_df["classification"] == "primary", "lemmatised_text"].dropna())
comparative_text = " ".join(corpus_df.loc[corpus_df["classification"] == "comparative", "lemmatised_text"].dropna())

make_wordcloud(primary_text, "Most Frequent Terms - Primary Documents (All 3 Themes)", "outputs/charts/wordcloud_primary.png")
make_wordcloud(comparative_text, "Most Frequent Terms - Comparative Documents (2 Themes)", "outputs/charts/wordcloud_comparative.png")

print("Saved word clouds to outputs/charts/")

# Topic sizes (top 15) - BERTopic
top_topics = topic_info[topic_info["Topic"] != -1].head(15)

fig, ax = plt.subplots(figsize=(10, 6))
ax.barh(top_topics["Name"], top_topics["Count"], color="#4C72B0")
ax.set_xlabel("Documents")
ax.set_title("Top 15 Topics by Size (BERTopic)")
ax.invert_yaxis()
plt.tight_layout()
plt.savefig("outputs/charts/topic_sizes.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved outputs/charts/topic_sizes.png")

"""## 16. Save final dataset

Everything downstream analysis needs, in one bundle.
"""

corpus_df.to_csv("outputs/corpus_final.csv", index=False)          # full document-level dataset
datapoints_df.to_csv("outputs/datapoints_final.csv", index=False)  # sentence-level
paragraphs_df.to_csv("outputs/paragraphs_final.csv", index=False)  # paragraph-level

for _, row in corpus_df.iterrows():
    safe_name = re.sub(r"[^a-zA-Z0-9]+", "_", f"{row['org_name']}_{row['url'][-40:]}").strip("_")[:120] + ".txt"
    with open(os.path.join("corpus", safe_name), "w", encoding="utf-8") as f:
        f.write(row["clean_text"])

print("=" * 65)
print("FINAL SUMMARY")
print("=" * 65)
print(f"Documents:  {len(corpus_df)}  (target: >= {MIN_DOCUMENTS})")
print(f"Datapoints: {len(datapoints_df):,}  (target: >= {MIN_DATAPOINTS:,})")
print(f"Topics:     {n_topics}")
print()
print("Files saved to outputs/:")
print("  corpus_final.csv              - one row per document: text, keyword tags,")
print("                                    classification, topic, sentiment")
print("  datapoints_final.csv          - one row per sentence-level datapoint")
print("  paragraphs_final.csv          - one row per paragraph-level datapoint")
print("  excluded_documents_log.csv    - documents dropped by keyword filtering")
print("  topic_info.csv                - BERTopic topic sizes and top words")
print("  topic_theme_centrality.csv    - theme prevalence per topic (H2 evidence)")
print("  cooccurrence_results.xlsx     - all 4 levels of co-occurrence stats")
print("  hypothesis_summary.csv        - consolidated H1/H2/H3 NLP evidence")
print("  descriptive_statistics.csv    - corpus-level descriptive stats")
print("  charts/corpus_overview.png    - 6-panel corpus/sentiment overview")
print("  charts/cooccurrence_matrices.png - 4-level co-occurrence heatmaps")
print("  charts/topic_sizes.png        - top 15 BERTopic topics")
print("=" * 65)

import shutil
shutil.make_archive("nlp_pipeline_bundle", "zip", ".", "outputs")

try:
    from google.colab import files
    print("Running in Colab - downloading nlp_pipeline_bundle.zip")
    files.download("nlp_pipeline_bundle.zip")
except ImportError:
    print("Not running in Colab - find nlp_pipeline_bundle.zip in the working directory.")

"""## 17. Export final dataset

A single, standalone export of the final **document-level** dataset - separate
from the full `outputs/` bundle above, so you can download just this one file to
upload

Produces two versions of the same data:
- **`final_dataset.csv`** - plain CSV
- **`final_dataset.xlsx`** - the same data plus a **Codebook** sheet

"""

# Column order chosen for readability - identifying info first, then keyword
# tags, then classification/topic/sentiment results. Full document text is
# included but placed last so the spreadsheet doesn't open with a giant wall
# of text in column A.
appendix_columns = [
    "url", "org_name", "doc_type", "source_category", "hypothesis_tag",
    "word_count", "lemma_word_count",
    "has_ai_sc", "has_sc_res", "has_i5", "ai_count", "res_count", "i5_count",
    "theme_count", "classification",
    "topic",
    "sentiment_label", "sentiment_positive", "sentiment_neutral", "sentiment_negative",
    "has_negative_chunk", "max_negative_chunk_prob",
    "clean_text",
]
appendix_columns = [c for c in appendix_columns if c in corpus_df.columns]
final_dataset = corpus_df[appendix_columns].copy()

# --- CSV (for GitHub) ---
final_dataset.to_csv("final_dataset.csv", index=False)

# --- Excel with a Codebook sheet (for the dissertation appendix) ---
codebook_rows = [
    {"Column": "url", "Description": "Source document URL"},
    {"Column": "org_name", "Description": "Publishing organisation"},
    {"Column": "doc_type", "Description": "html or pdf"},
    {"Column": "source_category", "Description": "One of the five methodology source categories (or supplementary academic)"},
    {"Column": "hypothesis_tag", "Description": "Which hypothesis this source was originally selected to inform (H1/H2/H3)"},
    {"Column": "word_count", "Description": "Word count of clean_text (pre-lemmatisation)"},
    {"Column": "lemma_word_count", "Description": "Word count after spaCy lemmatisation/stopword removal"},
    {"Column": "has_ai_sc", "Description": "True if document contains >=1 'AI in supply chain' keyword"},
    {"Column": "has_sc_res", "Description": "True if document contains >=1 'supply chain resilience' keyword"},
    {"Column": "has_i5", "Description": "True if document contains >=1 'Industry 5.0' keyword"},
    {"Column": "ai_count", "Description": "Count of AI-in-supply-chain keyword matches"},
    {"Column": "res_count", "Description": "Count of supply-chain-resilience keyword matches"},
    {"Column": "i5_count", "Description": "Count of Industry-5.0 keyword matches"},
    {"Column": "theme_count", "Description": "Number of the three theme keyword sets matched (0-3)"},
    {"Column": "classification", "Description": "primary (3/3 themes), comparative (2/3 themes), or excluded (<2, not in this file)"},
    {"Column": "topic", "Description": "BERTopic topic ID (-1 = outlier/unassigned); see topic_info.csv for keywords per topic"},
    {"Column": "sentiment_label", "Description": "Document-level sentiment (majority vote across text chunks): positive/neutral/negative"},
    {"Column": "sentiment_positive", "Description": "Mean positive-class probability across chunks"},
    {"Column": "sentiment_neutral", "Description": "Mean neutral-class probability across chunks"},
    {"Column": "sentiment_negative", "Description": "Mean negative-class probability across chunks"},
    {"Column": "has_negative_chunk", "Description": "True if >=1 individual text chunk was classified negative, even if the document's overall label is not"},
    {"Column": "max_negative_chunk_prob", "Description": "Highest negative-class probability seen in any single chunk of the document"},
    {"Column": "clean_text", "Description": "Full cleaned document text (lowercased, boilerplate/URLs stripped, paragraph breaks preserved)"},
]
codebook_df = pd.DataFrame([r for r in codebook_rows if r["Column"] in appendix_columns])

with pd.ExcelWriter("final_dataset.xlsx", engine="openpyxl") as writer:
    final_dataset.to_excel(writer, sheet_name="Data", index=False)
    codebook_df.to_excel(writer, sheet_name="Codebook", index=False)

print(f"Exported final_dataset.csv and final_dataset.xlsx ({len(final_dataset)} documents, "
      f"{len(appendix_columns)} columns)")

try:
    from google.colab import files
    files.download("final_dataset.csv")
    files.download("final_dataset.xlsx")
    print("Downloading final_dataset.csv and final_dataset.xlsx")
except ImportError:
    print("Not running in Colab - find final_dataset.csv / final_dataset.xlsx "
          "in the current working directory.")

try:
    from google.colab import files
    print("Downloading datapoints_final.csv")
    files.download("outputs/datapoints_final.csv")
except ImportError:
    print("Not running in Colab - find outputs/datapoints_final.csv in the working directory.")