# -*- coding: utf-8 -*-
"""Survey_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4aDFKCTMgm_QFfhQsXUmCJGZI6cmaOm

# Survey Data Analysis
## AI Adoption, Supply Chain Resilience, and Industry 5.0 Readiness

Implements the four-stage analysis described in the methodology, on the
Microsoft Forms export (`Survey_Data.xlsx`), plus visualisations at each stage.

1. **Data cleaning** - remove screening-logic bypasses, incomplete responses, and straight-lined responses.
2. **Descriptive statistics** - demographic frequencies, item-level means/SDs (+ charts).
3. **Reliability analysis** - Cronbach's alpha per construct (+ chart).
4. **Composite scores & correlation (H2)** - construct-level composites, Pearson correlations (+ heatmap, scatterplots).
5. **Sequential hierarchical regression (H1 & H3)** - a single three-block model: controls (Block 1), + AI Adoption (Block 2, tests H1), + Industry 5.0 Readiness (Block 3, tests H3 via R^2 change) (+ coefficient and R^2-by-block charts).

## 1. Install libraries & load data
"""

!pip install -q pingouin openpyxl
print("Libraries installed.")

import numpy as np
import pandas as pd
import pingouin as pg
from scipy import stats
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 140)
sns.set_style("whitegrid")

print("Setup complete.")

def download_chart(filepath):
    """Trigger an individual browser download for one chart file (Colab only)."""
    try:
        from google.colab import files
        files.download(filepath)
    except ImportError:
        pass  # not running in Colab - file is still saved locally

print("Chart download helper ready.")

import os

FILE_PATH = "Survey Data.xlsx"

if not os.path.exists(FILE_PATH):
    try:
        from google.colab import files
        print(f"{FILE_PATH} not found - please upload it.")
        uploaded = files.upload()
        FILE_PATH = list(uploaded.keys())[0]
    except ImportError:
        raise FileNotFoundError(f"Could not find {FILE_PATH}. Upload it and re-run this cell.")

raw_df = pd.read_excel(FILE_PATH, sheet_name=0)
print(f"Loaded {len(raw_df)} rows, {len(raw_df.columns)} columns")
raw_df.head()

"""## 2. Column mapping (confirmed by question text)

Non-item columns and the 14 Likert items are identified by matching keywords
from their actual question wording, not by column position.

"""

def find_col(keyword):
    matches = [c for c in raw_df.columns if keyword.lower() in str(c).lower()]
    if not matches:
        raise ValueError(f"No column found matching {keyword!r}")
    return matches[0]

COL_CONSENT   = find_col("consent to participate")
COL_SCREENING = find_col("procurement, logistics")
COL_REGION    = find_col("region is your organization")
COL_ORG_SIZE  = find_col("organizational size")
COL_JOB_LEVEL = find_col("current job level")

AI_ADOPTION_KEYWORDS = [
    "uses AI-based tools in supply chain",
    "improved the speed of decision-making",
    "AI-generated insights are helpful",
    "confident using AI-based supply chain tools",
]
SC_RESILIENCE_KEYWORDS = [
    "quickly adjust production or distribution plans",
    "rapidly reconfigure our supply network",
    "real-time visibility into inventory",
    "adjust order volumes at short notice",
    "hold buffer inventory",
]
INDUSTRY5_KEYWORDS = [
    "designed to support, not replace, human decision-makers",
    "involved in decisions about how AI tools are implemented",
    "helped reduce waste or resource use",
    "Sustainability considerations are factored",
    "used proactively to anticipate disruptions",
]

ITEM_CONSTRUCT_MAP = {
    "AI_Adoption": [find_col(k) for k in AI_ADOPTION_KEYWORDS],
    "SC_Resilience": [find_col(k) for k in SC_RESILIENCE_KEYWORDS],
    "Industry5_Readiness": [find_col(k) for k in INDUSTRY5_KEYWORDS],
}

item_cols = [c for cols in ITEM_CONSTRUCT_MAP.values() for c in cols]
assert len(item_cols) == 14, f"Expected 14 item columns, found {len(item_cols)}"

print("Construct -> item columns (confirmed via question text):")
for construct, cols in ITEM_CONSTRUCT_MAP.items():
    print(f"\n{construct} ({len(cols)} items):")
    for c in cols:
        print(f"    {c!r}")

"""## 3. Data cleaning

Four steps, applied in order, with the sample size reported after each so the
cleaning funnel is fully auditable in the findings chapter.

"""

LIKERT_MAP = {
    "Strongly agree": 1,
    "Agree": 2,
    "Neither agree nor disagree": 3,
    "Disagree": 4,
    "Strongly disagree": 5,
}

df = raw_df.copy()
n_start = len(df)
print(f"Step 0 - Raw responses: {n_start}")

# --- Step 1: remove consent refusals and screening-logic bypasses ---
df = df[df[COL_CONSENT].astype(str).str.strip().str.lower().str.startswith("yes")]
print(f"Step 1a - After removing consent refusals: {len(df)} (removed {n_start - len(df)})")

n_before_screen = len(df)
df = df[df[COL_SCREENING].astype(str).str.strip().str.lower() == "yes"]
print(f"Step 1b - After removing screening-logic bypasses (role not "
      f"procurement/logistics/SC): {len(df)} (removed {n_before_screen - len(df)})")

# --- Step 2: recode Likert text to numeric (Strongly agree=1 ... Strongly disagree=5) ---
for col in item_cols:
    df[col] = df[col].map(LIKERT_MAP)

# --- Step 3: remove responses missing more than half of the 14 Likert items ---
n_before_missing = len(df)
missing_count = df[item_cols].isna().sum(axis=1)
df = df[missing_count <= (len(item_cols) / 2)]
print(f"\nStep 2 - After removing responses with >50% of Likert items missing: "
      f"{len(df)} (removed {n_before_missing - len(df)})")

# --- Step 4: remove straight-lined responses (identical value across ALL 14 items) ---
n_before_straightline = len(df)
complete_rows = df[item_cols].notna().all(axis=1)
is_straightlined = complete_rows & (df[item_cols].nunique(axis=1) == 1)
straightliners_df = df[is_straightlined].copy()
df = df[~is_straightlined]
print(f"Step 3 - After removing straight-lined responses (same value across all "
      f"14 items): {len(df)} (removed {len(straightliners_df)})")

print(f"\nFinal cleaned sample: {len(df)} / {n_start} original responses "
      f"({len(df) / n_start:.1%} retained)")

straightliners_df.to_csv("straightlined_responses_removed.csv", index=False)
df.to_csv("cleaned_survey_data.csv", index=False)
print("Saved cleaned_survey_data.csv and straightlined_responses_removed.csv")

# --- Visualisation: cleaning funnel ---
funnel_labels = ["Raw\nresponses", "After consent\n+ screening", "After missing-\ndata filter", "After straight-\nline removal"]
funnel_values = [n_start, n_before_missing, n_before_straightline, len(df)]

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(funnel_labels, funnel_values, color="#4C72B0", edgecolor="white")
for bar, val in zip(bars, funnel_values):
    ax.text(bar.get_x() + bar.get_width()/2, val + 3, str(val), ha="center", fontweight="bold")
ax.set_title("Data Cleaning Funnel")
ax.set_ylabel("Responses")
plt.tight_layout()
plt.savefig("chart_01_cleaning_funnel.png", dpi=150, bbox_inches="tight")
download_chart("chart_01_cleaning_funnel.png")
plt.show()

"""## 4. Stage 1 - Descriptive statistics"""

print("=" * 65)
print("DEMOGRAPHIC FREQUENCY DISTRIBUTIONS")
print("=" * 65)

for label, col in [("Job level", COL_JOB_LEVEL), ("Region", COL_REGION), ("Organisation size", COL_ORG_SIZE)]:
    print(f"\n{label}:")
    freq = df[col].value_counts(dropna=False)
    pct = df[col].value_counts(normalize=True, dropna=False) * 100
    summary = pd.DataFrame({"n": freq, "%": pct.round(1)})
    print(summary.to_string())

# --- Visualisation: demographic bar charts ---
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
for ax, (label, col) in zip(axes, [("Job level", COL_JOB_LEVEL), ("Region", COL_REGION), ("Organisation size", COL_ORG_SIZE)]):
    counts = df[col].value_counts()
    ax.bar(counts.index, counts.values, color="#55A868", edgecolor="white")
    ax.set_title(label)
    ax.tick_params(axis="x", rotation=30)
    for i, v in enumerate(counts.values):
        ax.text(i, v + 3, str(v), ha="center", fontsize=9)
plt.tight_layout()
plt.savefig("chart_02_demographics.png", dpi=150, bbox_inches="tight")
download_chart("chart_02_demographics.png")
plt.show()

print("=" * 65)
print("ITEM-LEVEL DESCRIPTIVE STATISTICS (1 = Strongly agree, 5 = Strongly disagree)")
print("=" * 65)

item_desc_rows = []
for construct, cols in ITEM_CONSTRUCT_MAP.items():
    for col in cols:
        item_desc_rows.append({
            "Construct": construct, "Item": col[:60],
            "N": df[col].notna().sum(), "Mean": round(df[col].mean(), 2),
            "SD": round(df[col].std(), 2),
        })

item_desc_df = pd.DataFrame(item_desc_rows)
item_desc_df.to_csv("item_descriptive_statistics.csv", index=False)
print(item_desc_df.to_string(index=False))
print("\nSaved item_descriptive_statistics.csv")

# --- Visualisation: item means with SD error bars, coloured by construct ---
construct_colors = {"AI_Adoption": "#4C72B0", "SC_Resilience": "#55A868", "Industry5_Readiness": "#C44E52"}

fig, ax = plt.subplots(figsize=(10, 7))
y_pos = range(len(item_desc_df))
colors = [construct_colors[c] for c in item_desc_df["Construct"]]
ax.barh(y_pos, item_desc_df["Mean"], xerr=item_desc_df["SD"], color=colors, edgecolor="white", capsize=3)
ax.set_yticks(y_pos)
ax.set_yticklabels(item_desc_df["Item"], fontsize=8)
ax.invert_yaxis()
ax.set_xlabel("Mean (1 = Strongly agree, 5 = Strongly disagree)")
ax.set_title("Item Means +/- SD, by Construct")
ax.axvline(3, color="grey", linestyle="--", linewidth=1)

from matplotlib.patches import Patch
legend_elems = [Patch(facecolor=c, label=name) for name, c in construct_colors.items()]
ax.legend(handles=legend_elems, loc="lower right")

plt.tight_layout()
plt.savefig("chart_03_item_means.png", dpi=150, bbox_inches="tight")
download_chart("chart_03_item_means.png")
plt.show()

"""## 5. Stage 2 - Reliability analysis (Cronbach's alpha)

Threshold: alpha >= 0.70 (Peterson, 1994). If a construct falls below this, the
item with the lowest item-total correlation is identified and removed, and
alpha is recalculated.

"""

def cronbach_with_diagnostics(data, cols, construct_name, threshold=0.70):
    working_cols = list(cols)
    subset = data[working_cols].dropna()

    alpha, ci = pg.cronbach_alpha(data=subset)
    print(f"\n{construct_name} - initial alpha (k={len(working_cols)} items, n={len(subset)}): "
          f"{alpha:.3f}  95% CI [{ci[0]:.3f}, {ci[1]:.3f}]")

    removed_item = None
    if alpha < threshold:
        print(f"  Below the {threshold} threshold - examining item-total correlations...")
        item_total_corrs = {}
        for col in working_cols:
            rest = [c for c in working_cols if c != col]
            item_total_corrs[col] = subset[col].corr(subset[rest].mean(axis=1))

        for col, corr in sorted(item_total_corrs.items(), key=lambda x: x[1]):
            print(f"    Item-total r = {corr:.3f}  ({col[:60]!r})")

        removed_item = min(item_total_corrs, key=item_total_corrs.get)
        working_cols = [c for c in working_cols if c != removed_item]
        subset2 = data[working_cols].dropna()
        alpha2, ci2 = pg.cronbach_alpha(data=subset2)
        print(f"\n  Removed weakest item ({removed_item[:60]!r}, item-total r="
              f"{item_total_corrs[removed_item]:.3f}).")
        print(f"  Recalculated alpha (k={len(working_cols)} items, n={len(subset2)}): "
              f"{alpha2:.3f}  95% CI [{ci2[0]:.3f}, {ci2[1]:.3f}]")
        alpha, ci = alpha2, ci2
    else:
        print(f"  Meets the {threshold} threshold - no items removed.")

    return {
        "construct": construct_name, "final_items": working_cols,
        "alpha": alpha, "ci_low": ci[0], "ci_high": ci[1], "removed_item": removed_item,
    }


print("=" * 65)
print("RELIABILITY ANALYSIS")
print("=" * 65)

reliability_results = {}
for construct, cols in ITEM_CONSTRUCT_MAP.items():
    reliability_results[construct] = cronbach_with_diagnostics(df, cols, construct)

reliability_summary = pd.DataFrame([
    {"Construct": r["construct"], "Final k": len(r["final_items"]),
     "Cronbach alpha": round(r["alpha"], 3), "95% CI": f"[{r['ci_low']:.3f}, {r['ci_high']:.3f}]",
     "Item removed": (r["removed_item"][:50] + "...") if r["removed_item"] else "None"}
    for r in reliability_results.values()
])
reliability_summary.to_csv("reliability_summary.csv", index=False)
print("\n" + "=" * 65)
print("RELIABILITY SUMMARY")
print("=" * 65)
print(reliability_summary.to_string(index=False))
print("\nSaved reliability_summary.csv")

# --- Visualisation: Cronbach's alpha per construct vs threshold ---
fig, ax = plt.subplots(figsize=(8, 5))
constructs = [r["construct"] for r in reliability_results.values()]
alphas = [r["alpha"] for r in reliability_results.values()]
colors = ["#55A868" if a >= 0.70 else "#C44E52" for a in alphas]

bars = ax.bar(constructs, alphas, color=colors, edgecolor="white")
ax.axhline(0.70, color="black", linestyle="--", linewidth=1, label="Threshold (0.70)")
for bar, val in zip(bars, alphas):
    ax.text(bar.get_x() + bar.get_width()/2, val + 0.02, f"{val:.3f}", ha="center", fontweight="bold")
ax.set_ylim(0, 1.0)
ax.set_ylabel("Cronbach's alpha")
ax.set_title("Construct Reliability (Cronbach's alpha)")
ax.legend()
plt.tight_layout()
plt.savefig("chart_04_reliability.png", dpi=150, bbox_inches="tight")
download_chart("chart_04_reliability.png")
plt.show()

"""## 6. Stage 3 - Composite scores & correlation analysis

Composite scores use each construct's **final item set** from the reliability
analysis above (i.e. excluding any item removed for poor internal consistency).

"""

for construct, result in reliability_results.items():
    df[construct] = df[result["final_items"]].mean(axis=1)

print("Composite score descriptives:")
print(df[list(ITEM_CONSTRUCT_MAP.keys())].describe().round(2).to_string())

print("=" * 65)
print("PEARSON CORRELATIONS BETWEEN COMPOSITE SCORES")
print("=" * 65)
print("(Note: all three composites use the SAME reverse-coded scale direction")
print(" (1=Strongly agree ... 5=Strongly disagree), so a POSITIVE r means a")
print(" POSITIVE real-world relationship - no sign flip needed between them.)")
print()

corr_pairs = [
    ("AI_Adoption", "SC_Resilience", "H1 - AI Adoption vs SC Resilience"),
    ("AI_Adoption", "Industry5_Readiness", "H2 - AI Adoption vs Industry 5.0 Readiness"),
    ("Industry5_Readiness", "SC_Resilience", "H3 context - Industry 5.0 Readiness vs SC Resilience"),
]

correlation_results = []
for v1, v2, label in corr_pairs:
    valid = df[[v1, v2]].dropna()
    r, p = stats.pearsonr(valid[v1], valid[v2])
    sig = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else "n.s."
    direction = "positive (supportive)" if r > 0 else "negative (not supportive)"
    print(f"{label}")
    print(f"  r={r:.3f}, p={p:.4f} {sig}  (n={len(valid)}) -> real-world direction: {direction}")
    correlation_results.append({"Comparison": label, "r": round(r, 3), "p_value": round(p, 4),
                                 "n": len(valid), "Significance": sig})

pd.DataFrame(correlation_results).to_csv("composite_correlations.csv", index=False)
print("\nSaved composite_correlations.csv")

# --- Visualisation: correlation heatmap ---
composite_cols = list(ITEM_CONSTRUCT_MAP.keys())
corr_matrix = df[composite_cols].corr()

fig, ax = plt.subplots(figsize=(6, 5))
sns.heatmap(corr_matrix, annot=True, fmt=".3f", cmap="RdBu_r", vmin=-1, vmax=1,
            linewidths=0.5, linecolor="white", ax=ax, cbar_kws={"shrink": 0.8})
ax.set_title("Composite Score Correlation Matrix")
plt.tight_layout()
plt.savefig("chart_05_correlation_heatmap.png", dpi=150, bbox_inches="tight")
download_chart("chart_05_correlation_heatmap.png")
plt.show()

# --- Visualisation: pairwise scatterplots with regression lines ---
fig, axes = plt.subplots(1, 3, figsize=(16, 5))
scatter_pairs = [
    ("AI_Adoption", "SC_Resilience", "H1"),
    ("AI_Adoption", "Industry5_Readiness", "H2"),
    ("Industry5_Readiness", "SC_Resilience", "H3 context"),
]
for ax, (x, y, label) in zip(axes, scatter_pairs):
    sns.regplot(data=df, x=x, y=y, ax=ax, scatter_kws={"alpha": 0.3, "s": 15}, line_kws={"color": "#C44E52"})
    r, p = stats.pearsonr(df[x].dropna(), df.loc[df[x].notna(), y].dropna())
    ax.set_title(f"{label}: r={r:.3f}, p={p:.4f}")
plt.tight_layout()
plt.savefig("chart_06_scatterplots.png", dpi=150, bbox_inches="tight")
download_chart("chart_06_scatterplots.png")
plt.show()

"""## 7. Stage 4 - Hierarchical Multiple Regression (H1 & H3)

This stage implements a single hierarchical multiple regression model with three sequential blocks to test both Hypothesis 1 (H1) and Hypothesis 3 (H3), as per the specified methodology.

Dependent variable: Supply Chain Resilience composite.

-   **Block 1**: Control variables (job level, geographic region, organisation size), dummy-coded, are entered.
    *   *Purpose*: To establish how much variance in Supply Chain Resilience they account for on their own.

-   **Block 2**: AI Adoption composite is added to the model.
    *   *Purpose*: To isolate its relationship with Supply Chain Resilience after accounting for the control variables.
    *   **H1 test**: The standardised Beta and associated p-value for AI Adoption at this stage provide the primary test of H1. A positive and statistically significant Beta supports H1.

-   **Block 3**: Industry 5.0 Readiness composite is added to the model, after AI Adoption is already present.
    *   *Purpose*: To determine the additional variance explained by Industry 5.0 Readiness.
    *   **H3 test**: The R-squared change between Block 2 and Block 3 indicates how much additional variance in Supply Chain Resilience Industry 5.0 Readiness explains beyond AI Adoption alone. H3 is supported where this R-squared change is statistically significant, and the standardised Beta and p-value for Industry 5.0 Readiness in Block 3 are positive and significant. This provides direct evidence that Industry 5.0 Readiness explains additional variance in Supply Chain Resilience after AI Adoption has been included in the model.
"""

reg_df = df.dropna(subset=["SC_Resilience", "AI_Adoption", "Industry5_Readiness",
                            COL_JOB_LEVEL, COL_REGION, COL_ORG_SIZE]).copy()
print(f"Regression sample (complete cases on all model variables): {len(reg_df)}")

control_dummies = pd.get_dummies(
    reg_df[[COL_JOB_LEVEL, COL_REGION, COL_ORG_SIZE]],
    prefix=["JobLevel", "Region", "OrgSize"], drop_first=True
).astype(float)

control_col_names = list(control_dummies.columns)
print(f"\nControl variables (dummy-coded, reference category dropped): {control_col_names}")

def zscore(s):
    return (s - s.mean()) / s.std()

model_df = pd.concat([
    reg_df[["SC_Resilience", "AI_Adoption", "Industry5_Readiness"]].reset_index(drop=True),
    control_dummies.reset_index(drop=True)
], axis=1)

z_df = model_df.copy()
for col in ["SC_Resilience", "AI_Adoption", "Industry5_Readiness"] + control_col_names:
    if z_df[col].std() > 0:
        z_df[col] = zscore(z_df[col])

# Dependent variable
y = z_df["SC_Resilience"]

# --- Block 1: Controls only ---
X1_block = sm.add_constant(z_df[control_col_names])
model1 = sm.OLS(y, X1_block).fit()

# --- Block 2: Controls + AI Adoption ---
X2_block = sm.add_constant(z_df[control_col_names + ["AI_Adoption"]])
model2 = sm.OLS(y, X2_block).fit()

# --- Block 3: Controls + AI Adoption + Industry 5.0 Readiness ---
X3_block = sm.add_constant(z_df[control_col_names + ["AI_Adoption", "Industry5_Readiness"]])
model3 = sm.OLS(y, X3_block).fit()

# --- Calculate R^2 change for Block 2 from Block 1 ---
r2_change_2v1 = model2.rsquared - model1.rsquared
f_num_2v1 = (model2.rsquared - model1.rsquared) / (X2_block.shape[1] - X1_block.shape[1])
f_den_2v1 = (1 - model2.rsquared) / (len(z_df) - X2_block.shape[1] - 1)
f_change_2v1 = f_num_2v1 / f_den_2v1
df1_2v1 = X2_block.shape[1] - X1_block.shape[1]
df2_2v1 = len(z_df) - X2_block.shape[1] - 1
f_change_2v1_p = 1 - stats.f.cdf(f_change_2v1, df1_2v1, df2_2v1)

# --- Calculate R^2 change for Block 3 from Block 2 ---
r2_change_3v2 = model3.rsquared - model2.rsquared
f_num_3v2 = (model3.rsquared - model2.rsquared) / (X3_block.shape[1] - X2_block.shape[1])
f_den_3v2 = (1 - model3.rsquared) / (len(z_df) - X3_block.shape[1] - 1)
f_change_3v2 = f_num_3v2 / f_den_3v2
df1_3v2 = X3_block.shape[1] - X2_block.shape[1]
df2_3v2 = len(z_df) - X3_block.shape[1] - 1
f_change_3v2_p = 1 - stats.f.cdf(f_change_3v2, df1_3v2, df2_3v2)

print("=" * 65)
print("HIERARCHICAL MULTIPLE REGRESSION - DV: Supply Chain Resilience")
print("=" * 65)

print(f"\nBlock 1 (controls only): R^2 = {model1.rsquared:.3f}")
print(f"Block 2 (+ AI Adoption): R^2 = {model2.rsquared:.3f} (Delta R^2 from Block 1 = {r2_change_2v1:.3f})")
print(f"  F change({df1_2v1},{df2_2v1}) = {f_change_2v1:.3f}, p = {f_change_2v1_p:.4f}")
print(f"Block 3 (+ Industry 5.0 Readiness): R^2 = {model3.rsquared:.3f} (Delta R^2 from Block 2 = {r2_change_3v2:.3f})")
print(f"  F change({df1_3v2},{df2_3v2}) = {f_change_3v2:.3f}, p = {f_change_3v2_p:.4f}")

# --- H1 Interpretation ---
print("\n" + "=" * 65)
print("H1 INTERPRETATION (from Block 2, AI Adoption's Beta)")
print("=" * 65)
ai_beta_h1 = model2.params["AI_Adoption"]
ai_p_h1 = model2.pvalues["AI_Adoption"]
h1_supported = (ai_beta_h1 > 0) and (ai_p_h1 < 0.05)
print('H1 - "AI Adoption is positively and significantly related to Supply Chain Resilience after controlling for job level, geographic region, and organisation size."')
print(f"  AI Adoption (Block 2): Beta = {ai_beta_h1:.3f}, p = {ai_p_h1:.4f}")
print(f"  H1: {'SUPPORTED' if h1_supported else 'NOT SUPPORTED'}")

# --- H3 Interpretation ---
print("\n" + "=" * 65)
print("H3 INTERPRETATION (from Block 3, Industry 5.0 Readiness Beta and R^2 Change)")
print("=" * 65)
i5_beta_h3 = model3.params["Industry5_Readiness"]
i5_p_h3 = model3.pvalues["Industry5_Readiness"]
h3_supported = (i5_beta_h3 > 0) and (i5_p_h3 < 0.05) and (f_change_3v2_p < 0.05)
print('H3 - "Industry 5.0 Readiness explains additional variance in Supply Chain Resilience after AI Adoption has been included in the model."')
print(f"  Industry 5.0 Readiness (Block 3): Beta = {i5_beta_h3:.3f}, p = {i5_p_h3:.4f}")
print(f"  R^2 change (Block 2 -> 3) = {r2_change_3v2:.3f}, p = {f_change_3v2_p:.4f}")
print(f"  H3: {'SUPPORTED' if h3_supported else 'NOT SUPPORTED'} (requires positive, significant Beta for Industry 5.0 Readiness AND a significant R^2 change)")


# Save the coefficients for the final model (Block 3)
beta_table_block3 = pd.DataFrame({
    "Beta (standardised)": model3.params, "SE": model3.bse,
    "t": model3.tvalues, "p": model3.pvalues,
}).round(4)
beta_table_block3.to_csv("regression_block3_coefficients_h1_h3_combined.csv")
print("\nSaved regression_block3_coefficients_h1_h3_combined.csv")

from statsmodels.stats.outliers_influence import variance_inflation_factor

print("\n" + "=" * 65)
print("MULTICOLLINEARITY DIAGNOSTICS (VIF & Tolerance) - Block 3 Predictors (final model)")
print("=" * 65)

# Prepare the design matrix X for VIF calculation, excluding the constant
X_vif = sm.add_constant(z_df[control_col_names + ["AI_Adoption", "Industry5_Readiness"]]).drop(columns='const')

vif_data = pd.DataFrame()
vif_data["Variable"] = X_vif.columns
vif_data["VIF"] = [variance_inflation_factor(X_vif.values, i) for i in range(X_vif.shape[1])]
vif_data["Tolerance"] = 1 / vif_data["VIF"]

print(vif_data.round(3).to_string(index=False))

# --- Visualisation: standardised Beta coefficients with 95% CI, Block 2 ---
conf_int = model2.conf_int()
plot_vars = [v for v in model2.params.index if v != "const"]

fig, ax = plt.subplots(figsize=(9, max(4, len(plot_vars) * 0.4)))
y_pos = range(len(plot_vars))
betas = [model2.params[v] for v in plot_vars]
errors = [[model2.params[v] - conf_int.loc[v, 0] for v in plot_vars],
          [conf_int.loc[v, 1] - model2.params[v] for v in plot_vars]]
colors = ["#4C72B0" if v in ["AI_Adoption", "Industry5_Readiness"] else "#8C8C8C" for v in plot_vars]

ax.errorbar(betas, y_pos, xerr=errors, fmt="o", color="black", ecolor="grey", capsize=3)
for i, (v, b, c) in enumerate(zip(plot_vars, betas, colors)):
    ax.scatter(b, i, color=c, s=80, zorder=3)
ax.axvline(0, color="red", linestyle="--", linewidth=1)
ax.set_yticks(y_pos)
ax.set_yticklabels(plot_vars)
ax.invert_yaxis()
ax.set_xlabel("Standardised Beta (95% CI)")
ax.set_title("Block 2 Regression Coefficients - DV: SC Resilience")
plt.tight_layout()
plt.savefig("chart_07_regression_coefficients.png", dpi=150, bbox_inches="tight")
download_chart("chart_07_regression_coefficients.png")
plt.show()

"""## 8. Stage 4 (Continued) - Hierarchical Multiple Regression Visualisations

This section provides visualisations related to the hierarchical regression performed in the previous section (Section 7), which tests both H1 and H3. The code for the sequential entry regression for H3 is now integrated into Section 7.
"""

# Use the STANDARDISED z_df (from Section 7), not the raw model_df - otherwise
# predictors are on the raw 1-5 scale while y is standardised, which produces
# nonsensical "standardised" coefficients (this was caught by testing against
# real data - Block 3 initially returned a const of -6.7 and Betas above 1.0,
# which are impossible for a genuinely standardised regression).
X1_h3 = sm.add_constant(z_df[control_col_names])
h3_model1 = sm.OLS(y, X1_h3).fit()

X2_h3 = sm.add_constant(z_df[control_col_names + ["AI_Adoption"]])
h3_model2 = sm.OLS(y, X2_h3).fit()

X3_h3 = sm.add_constant(z_df[control_col_names + ["AI_Adoption", "Industry5_Readiness"]])
h3_model3 = sm.OLS(y, X3_h3).fit()

r2_change_3v2 = h3_model3.rsquared - h3_model2.rsquared
f_num = (h3_model3.rsquared - h3_model2.rsquared) / (X3_h3.shape[1] - X2_h3.shape[1])
f_den = (1 - h3_model3.rsquared) / (len(model_df) - X3_h3.shape[1] - 1)
f_change_3v2 = f_num / f_den
d1_3v2 = X3_h3.shape[1] - X2_h3.shape[1]
d2_3v2 = len(model_df) - X3_h3.shape[1] - 1
f_change_3v2_p = 1 - stats.f.cdf(f_change_3v2, d1_3v2, d2_3v2)

print("=" * 65)
print("SEQUENTIAL HIERARCHICAL REGRESSION - H3 (DV: SC Resilience)")
print("=" * 65)
print(f"\nBlock 1 (controls only): R^2 = {h3_model1.rsquared:.3f}")
print(f"Block 2 (+ AI Adoption alone): R^2 = {h3_model2.rsquared:.3f} "
      f"(Delta R^2 from Block 1 = {h3_model2.rsquared - h3_model1.rsquared:.3f})")
print(f"Block 3 (+ Industry 5.0 Readiness): R^2 = {h3_model3.rsquared:.3f}")
print(f"\nDelta R^2 (Block 2 -> Block 3) = {r2_change_3v2:.3f}")
print(f"F change({d1_3v2}, {d2_3v2}) = {f_change_3v2:.3f}, p = {f_change_3v2_p:.4f}")

print("\n" + "-" * 65)
print("BLOCK 3 COEFFICIENTS")
print("-" * 65)
h3_beta_table = pd.DataFrame({
    "Beta (standardised)": h3_model3.params, "SE": h3_model3.bse,
    "t": h3_model3.tvalues, "p": h3_model3.pvalues,
}).round(4)
print(h3_beta_table.to_string())
h3_beta_table.to_csv("regression_h3_sequential_block3.csv")

print("\n" + "=" * 65)
print("H3 INTERPRETATION")
print("=" * 65)
i5_beta = h3_model3.params["Industry5_Readiness"]
i5_p = h3_model3.pvalues["Industry5_Readiness"]
h3_supported = (i5_beta > 0) and (i5_p < 0.05) and (f_change_3v2_p < 0.05)

print('H3 - "Industry 5.0 Readiness explains additional variance in Supply Chain')
print(' Resilience after AI Adoption has been included in the model."')
print(f"\n  AI Adoption alone (Block 2): Beta = {h3_model2.params['AI_Adoption']:.3f}, "
      f"p = {h3_model2.pvalues['AI_Adoption']:.4f}, R^2 = {h3_model2.rsquared:.3f}")
print(f"  Industry 5.0 Readiness (Block 3): Beta = {i5_beta:.3f}, p = {i5_p:.4f}")
print(f"  R^2 change (Block 2 -> 3) = {r2_change_3v2:.3f}, p = {f_change_3v2_p:.4f}")
print(f"\n  H3: {'SUPPORTED' if h3_supported else 'NOT SUPPORTED'} "
      f"(requires positive, significant Beta for Industry 5.0 Readiness AND "
      f"a significant R^2 change)")

print("\nSaved regression_h3_sequential_block3.csv")

# --- Visualisation: incremental R^2 across the three sequential blocks ---
block_labels = ["Block 1\n(controls only)", "Block 2\n(+ AI Adoption)", "Block 3\n(+ Industry 5.0\nReadiness)"]
block_r2 = [h3_model1.rsquared, h3_model2.rsquared, h3_model3.rsquared]

fig, ax = plt.subplots(figsize=(8, 5))
bars = ax.bar(block_labels, block_r2, color=["#8C8C8C", "#4C72B0", "#55A868"], edgecolor="white")
for bar, val in zip(bars, block_r2):
    ax.text(bar.get_x() + bar.get_width()/2, val + 0.01, f"{val:.3f}", ha="center", fontweight="bold")

# annotate the increment being tested for H3
ax.annotate(
    f"Delta R^2 = {r2_change_3v2:.3f}\np = {f_change_3v2_p:.4f}",
    xy=(2, block_r2[2]), xytext=(1.55, block_r2[2] + 0.08),
    arrowprops=dict(arrowstyle="->", color="black"),
    fontsize=10, ha="left"
)

ax.set_ylim(0, max(block_r2) + 0.15)
ax.set_ylabel("R^2 (variance in SC Resilience explained)")
ax.set_title("H3: Incremental Variance Explained by Industry 5.0 Readiness\n(after AI Adoption is already in the model)")
plt.tight_layout()
plt.savefig("chart_08_h3_sequential_r2.png", dpi=150, bbox_inches="tight")
download_chart("chart_08_h3_sequential_r2.png")
plt.show()

print("This chart shows the SEQUENTIAL test for H3: how much additional R^2")
print("Industry 5.0 Readiness contributes in Block 3, once AI Adoption's own")
print("contribution (Block 2) is already accounted for. A larger, significant")
print("jump from Block 2 to Block 3 supports H3.")

"""## 9. Save all outputs"""

import shutil

output_files = [
    "cleaned_survey_data.csv", "straightlined_responses_removed.csv",
    "item_descriptive_statistics.csv", "reliability_summary.csv",
    "composite_correlations.csv", "regression_block2_coefficients.csv",
    "regression_h3_sequential_block3.csv",
]
chart_files = [f"chart_0{i}_{name}.png" for i, name in enumerate(
    ["cleaning_funnel", "demographics", "item_means", "reliability",
     "correlation_heatmap", "scatterplots", "regression_coefficients", "h3_sequential_r2"], start=1)]

os.makedirs("survey_outputs", exist_ok=True)
os.makedirs("survey_outputs/charts", exist_ok=True)
for f in output_files:
    if os.path.exists(f):
        shutil.copy(f, os.path.join("survey_outputs", f))
for f in chart_files:
    if os.path.exists(f):
        shutil.copy(f, os.path.join("survey_outputs/charts", f))

shutil.make_archive("survey_analysis_outputs", "zip", ".", "survey_outputs")
print("Saved all outputs to survey_outputs/ and zipped as survey_analysis_outputs.zip")

try:
    from google.colab import files
    files.download("survey_analysis_outputs.zip")
except ImportError:
    print("Not running in Colab - find survey_analysis_outputs.zip in the working directory.")